### ISSUE TITLE
Pathfinding progress tracking

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1027]
- [x] Pathfinding on routes
- [ ] Pathfinding on routes + signaling routes
- [ ] Pathfinding on routes + signaling routes + timetable

**Comment by multun** [comment]
Completely obsolete, we now generate blocks and perform pathfinding on that
