### ISSUE TITLE
Define the data model for speed limits per train type / category

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#1326]
## Associated feature

Running time calculation with speed limits per train type

## Description

Many speed limits are defined for some types of train only.
We need to store and process these to properly simulate railway systems and hence get an accurate running time calculation.

## Goal

 - Understand how speed limits per train type work (is there some kind of inheritance between categories?)
 - Define how speed limits per train types are modeled and stored in database / railjson.

## Acceptance criteria

- [ ] Documentation about the findings and chosen design was written on the website
- [ ] The documentation contains an explanation of the constraints which motivated the decision
- [x] The documentation contains an example of a railjson speed limit for a given train type
- [x] The railjson schema has been changed accordingly
- [x] The services have been adapted with new railjson schema

**Comment by axrolld** [comment]
Small changes in the story description

**Comment by multun** [comment]
We discussed the matter with florian, and here is our thoughts:

- rolling stocks have intrinsic tags
- speed limits may only apply to a list of tags. when there are no tags, speed limits apply to all trains

## TODO

 - make a list of real world examples
 - how to express speed sections with different speeds depending on tags
 - how to express boolean logic with tags, if deemed necessary (hopefully not)

**Comment by flomonster** [comment]
After discussion with @nicolaswurtz  we should not need to evaluate boolean expressions. We can only use a filter per tag and keep the most constraining speed.

**Comment by multun** [comment]
@flomonster we haven't documented this in the website, which was a requirement, shall we?
