### ISSUE TITLE
UX design the Short Term DCM retrieval

### ISSUE THREAD

**Issue by carolnvg** [OpenRailAssociation/osrd#1430]
## Associated Feature / User Story

F3 : ST-DCM

## Description

Build a prototype of Short Term DCM retrieval. The user must be able to ask for a STDCM computation, with a specific operation mode. He/she must then be redirected to the simulation tab where the new train slot has been added.

## Goal

Getting a first representation of the STDCM feature, that will ease further developments.

## Tasks List

- [x] Explain function : objectives, param in, param out
- [x] Draw wireframe
- [x] Choose wireframe
- [ ] Make Mockups
- [ ] Validate Mockups

## Acceptance Criterias

- [x] The operation modes selectable by the user are : the next train slot available _(Le prochain disponible)_, the fastest one _(le plus rapide)_, the safest one _(le moins risqué)_
- [x] A tooltip must be placed next the dropdown list in order to give the user more information about the different options
- [x] The user is to expected to wait while the itinerary is processed
- [x] The use must be able to interrupt the computation process
- [x] A link to the mockups is published and available

## Definition of ready
- [x]  The user story is well defined
- [x] Acceptance criterias are defined
- [x] The individual responsible for validating the user story is assigned (@axrolld, @loic-hamelin  )
- [x] The team should understand how to demonstrate the features
- [x]  Does not depend on an missing feature
- [x]  Negociable with the implementation team
- [x] Valuable to the end users
- [x] Estimable by the implementation team
- [x] As small as it can be
- [x] Testable by the implementation team

## Definition of done
- [x] Acceptance criteria are met
- [x] Assumptions of User Story met
- [ ]  Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Feature ok-ed by Product Owner
- [ ] Documentation updated

**Comment by carolnvg** [comment]
After meeting 25/07/2022 and 26/07/2022

1. Card "Sillon de dernière minute" --> VALIDE
3. Page Parametrage --> VALIDE
4. Popup Loading AND button call to action --> VALIDE
5. Popup Success --> VALIDE
6. Popup Failed --> VALIDE
7. **[NEW] Page Commande --> TODO**

**Comment by carolnvg** [comment]
.
