### ISSUE TITLE
[meta] Search into lines

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#1636]
## User

- [X] Study officer
- [ ] Manager
- [ ] Front

## Description
Search into lines

## Goal
Permit user to look for a line by typing
- his name
- line number

## Acceptance criteria
- [x] Type text to search
- [x] Display search result layer
- [x] Select line and fly to the right place on map

## Difficulty

- [ ] easy
- [x] normal
- [ ] difficult
- [ ] extreme

## Definition of ready

- [X] The user story is well defined
- [X] Acceptance criterias are defined
- [X] The individual responsible for validating the user story is assigned
- [X] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [X] Negociable with the implementation team
- [X] Valuable to the end users
- [X] Estimable by the implementation team
- [X] As small as it can be
- [X] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by celine-sncf** [comment]
Split in two issues : 
https://github.com/DGEXSolutions/osrd/issues/3259
https://github.com/DGEXSolutions/osrd/issues/3260
