### ISSUE TITLE
Refactor editoast

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#1755]
## Associated Feature / User Story

Refacto editoast

## Description

- Use more trait `Object` `ErrorObject` `CacheObject`
- Less duplication
- Use `rtest`?
- Review architecture
- Have more abstraction

## Definition of ready

- [ ] The enabler story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the enbaler story is assigned
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by flomonster** [comment]
# Refactor Errors Generation

## Definition
  - `ObjectErrorCheck`: `Fn(&InfraCache, &Graph, ??Object??> -> Vec<InfraError>`
    - We have an issue here. We should refacto how the object system is done
    - We could give an object ref or have an `Object` trait but both solutions will imply to retrieve the object using InfraCache (which add overhead)
    - Do we need an enum for that (like RailjsonObject) ?
  - `ObjectTypeErrorCheck`: `Fn(&InfraCache, &Graph> -> Vec<InfraError>`
    - Used to handle errors such as overlapping switches (we can't process one object at the time)

## Tasks

- [ ] Separate functions that generate errors
- [ ] ErrorManager
  - The ErrorManager should be static or instanciate once
  - We should be able to register an `ObjectErrorCheck` with an object type and priority
  - We should be able to register an `ObjectErrorTypeCheck` with a type and priority
  - Given an InfraCache the ErrorManager should call error functions and generate all errors
  - The rule is that functions will be call for each object of the object type
  - When an error is found the next errors with lower priority won't be call



Can we use macro to register functions (that would be fancy). Example in python:
```python
@register_error(object_tpye=Detector, priority=3)
def my_error_generator(...):
   pass
```

```rust
#[register_error(object_tpye=ObjectType::Detector, priority=3)]
fn my_error_generator(...) { }
```

# Refactor Objects

Use traits:

- Object:
  - `get_id()`
  - `get_type()`
  - `new<T: AsRef<&str>>(id: T)` with default implementation()

Object -> Referencable

- Referencable
  - `get_ref()`

- Layer: Object
  - get_layer_slug() -> &str
  - get_generate_query() -> &str
  - refresh (auto implemented)
  - insert_update_list (auto implemented)
  - delete_list (auto implemented)
  - update (auto implemented)

**Comment by multun** [comment]
May I suggest another approach:

```rust
const TRACK_ERROR_GENERATORS: [ErrGenerator<TrackSection>, _] = [
    &[generate_error_a],
    &[generate_error_b, generate_error_c],
];

type ErrGenerator<T: ObjectType> = Fn(object: ObjectType) -> Vec<OSRDError>;

fn generate_error_a(track: TrackSection) -> Vec<OSRDError>{
}
```

**Comment by flomonster** [comment]
Done
