### ISSUE TITLE
[META] Backend conflict detection

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#2366]
## Description

Depends on #1046
Belongs to #1028

This is a backend feature.

## What is conflict detection

Conflict detection is about figuring out whether two independent trains would interfere if they ran simultaneously. An interference is defined as a slowdown, even temporary.

See the website for a more in-depth explanation ([fr](https://dgexsolutions.github.io/osrd-website/fr/developers/conflict-detection/) / en)

## Implementation plan

```mermaid
flowchart TD
    %% Conflict detection
    route-deadlines[Route set deadlines]
    route-resources[Routing resource timeline]
    min-spacing-timeline[Minimum spacing timeline]
    resources-timeline[Resource usage timeline]
    resource-database[Resource usage database]
    conflict-detection[Conflict detection]

    %% EDGES

    %% Conflict detection
    route-deadlines --> route-resources
    route-deadlines --> min-spacing-timeline
    route-resources --> resources-timeline
    min-spacing-timeline --> resources-timeline
    resources-timeline --> resource-database
    resource-database --> conflict-detection

```

## Depends on

- #2367
- #2368
- #2369

## Acceptance criteria

- [ ] A resource needs database was designed and implemented
- [ ] Conflicts can be detected using the needs database
- [ ] The needs database can be fed with standalone simulations
