### ISSUE TITLE
[Meta] Adapt services for electrical profiles

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#2743]
# Acceptance Criteria

- [ ] The simulation should take into account the electrical profiles
- [ ] The user can chose an electrical profile set to use 
- [ ] The user can see the electrical profiles along the path of the train + if they are effectively used

# Spec Techs
- Adapt core
  - #2777 
  - #2778 
- Adapt API:
  - #2779
  - #2891
- Adapt Front
  - #2733 
  - #2808 
- [ ] Check front is not broken

**Comment by Castavo** [comment]
Related PR (for the first items in the list): #2761

**Comment by flomonster** [comment]
Done
