### ISSUE TITLE
[meta] Populate Railjson from OpenStreetMap data (v1)

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#2874]
## Description

**Who is this feature for?**

European partners & external developers

**What should the user be able to achieve?**

- Load and view the railway infrastructure (produced from OpenStreetMap open data) of one european country
- Simulate at least one train on this infra

**Why do you think this feature would be valuable?**

- Allow european partners (or anyone !) to test OSRD on their countries
- Allow external developers to work on real-world data
- Demonstrate that any data source can be used as source for OSRD

## Acceptance criteria

* Infrastructure for one european country (Germany) is imported from OSM to Railjson
* This infra can be loaded and viewed on OSRD
* At least one train can be simulated on this infra

## Technical details

Create a first version of Railjson from OpenStreetMap (OSM) data that allows to simulate one train in Germany (long-term target in to import all of Europe but we must do the import country by country because signalling systems are different for each country + we may have to buy more RAM). 
Germany has been picked because of good data quality available on OSM and easily accessible documentation of the signalling system.
Out of scope for this first version: slopes, curves & loading_gauge_limit

- [x] Import OSM data (possible sources : dump and import to Postgres, API connexion, installing a dedicated Overpass server...) and create a new public repository to store OSM data for each country
- [x] Import tracks from OSM ((railway=rail or railway=narrow_gauge or railway=light_rail) & generate switches and buffer stops from geometrical deduction
- [x] Import operational points (railway=station or railway=halt) and speed sections (maxpeed=* or default maxspeed if data is missing)
- [x] Import signals from OSM to Railjson and generate detectors, buffer stops, routes
- [x] Move import scripts to editoast/main code to avoid duplicates > enabler for the next PI ?

**Comment by celine-sncf** [comment]
- Limit to one country because OSM tags can differ by country
   - Signals in good quality in OSM, documentation on the signalling system
- Signals should be imported in the first version
- Routes & detectors can be deduced from tracks & signals

2 tasks:
- Import
- Signalling system

For one country, should be ok.
For all of EU: not enough RAM > we may have to buy more RAM

**Comment by celine-sncf** [comment]
Steps:
- Import tracks from OSM to Railjson & generate switches 
- Read documentation on the country's signalling systems 
- Implement the signalling systems of the country in core
- Import signals from OSM to Railjson
- Generate detectors, buffer stops, routes

**Comment by celine-sncf** [comment]
Refined today with @Khoyo @flomonster & @multun , I updated the issue with adjustments & details

**Comment by Tristramg** [comment]
To be considered done, we need

- [x] tracks
- [x] buffer stops 
- [x] electrification
- [x] speed limits
- [x] signals
- [x] routes calculations    
- [x] being able to compute a path in Germany

What is not included in V1
- slopes
- fine signal handling

**Comment by celine-sncf** [comment]
tbc: https://github.com/orgs/osrd-project/projects/12/views/1?filterQuery=OSM&pane=issue&itemId=31960209
