### ISSUE TITLE
Add LRS support to RailJSON

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#2877]
## Description

RailJSON does not have any notion of what's a line, track, or linear referencing system.
This is a significant issue, as railway people expect to be able to locate objects using their LRS address.

Currently, there are no LRS addresses inside the core RailJSON spec, but line and tracks were added to the SNCF Extension. We should migrate it to the core spec for better support.

### Questions
- #6747 will impact the implementation plan
-  Impact on display, infra editor...

## Acceptance criteria

- [x] Survey and model a unified european railway LRS systems (done in https://github.com/osrd-project/osrd-confidential/issues/283)
- [ ] Implement this model into RailJSON

## Implementation plan

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

## Definition of ready

- **Data**
  - [x] Necessary data are clearly identified and defined (format, precision required, quality expected) > yes, as part of https://github.com/osrd-project/osrd-dags/issues/205
  - [x] The data is accessible (by webservice or file), the supplier is identified > yes, Gaïa + PM-SIG/Locinfra/Imajnet, already transformed in the input format
  - [x] A contact person is identified to answer our questions about the data > yes, filière Description du Réseau / Céline
  - [ ] Data documentation (access, understanding, quality) is available on Teams

- **UX**
  - [ ] A wireframe is ready
  - [ ] A mock-up is ready

- **PO**
  - [ ] Acceptance criteria are clear and understandable
  - [ ] The acceptance criteria are validated by users

- **Technical**
  - [ ] If required documentation is available on osrd.fr
  - [ ] Implementation plan is detailed and validated by maintainers

- **General**
  - [ ] WSJF values are filled
  - [ ] Validated by the PM

**Comment by axrolld** [comment]
Rebasculé en "A répartir" à l'atelier répartition/conception du 09/04 car besoin de conception une fois que le développement de la lib LRS sera plus abouti

**Comment by celine-sncf** [comment]
Moved to https://github.com/osrd-project/osrd-confidential/issues/488 because contains links to private repos
