### ISSUE TITLE
Implement slugs and meta data for operational studies

### ISSUE THREAD

**Issue by Math-R** [OpenRailAssociation/osrd#3109]
### Description and goal

The goal of slug routing is to allow people to share link to specific operational studies and to manage the routing of application differently, and the meta data will give a more friendly experience to navigate between the different studies 

### Acceptance criteria

- [ ] All projects/studies/scenario must have a unique slug in addition to their id
- [ ] Try to access projects/studies/scenario using an url with slug must work
- [ ] All projects/studies/scenario must set meta data during the navigation

**Comment by axrolld** [comment]
Done

**Comment by axrolld** [comment]
Everything's gathered [here](https://github.com/osrd-project/osrd-confidential/issues/335).
