### ISSUE TITLE
Define and implement new Standalone Train Simulation input and output

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#3187]
### Description and goal

These modifications must : 
- Simplify train schedules imports
- Make possible invalidation of train schedule

### Acceptance criteria

- [x] Inputs and outputs must be two distinct models
- [ ] make possible multiple ways to describe a train : 
     - Path + time
     - Operational point's time crossing

#### TODO

- [x] #3257
- [ ] State of the art must be done on common and internal train schedule models
     - Open data SNCF
     - GTFS
     - SIPH
     - PTO
- [ ] :warning: Have a set list of specifications (the user should be able to filter the schedules by geography, line name, dates, ...) :warning:

#### Alerts
1. Designing the new model required the product management team to know exactly what will be done with it:
 - must all the trains of a year be visible by a user or is it only a day and/or filtered trains ?
2. Operational studies are using stop durations while annual train schedules are using stop times
3. How can a user load the annual train schedule ?
4. How do we deal with  train stations (if tracks are not known) ?

#### Benefits of splitting the model :
- outputs can be computed asynchronously
- outputs can be invalidated while inputs are not
- will be possible to know that ouput is not up to date with input

Inputs and outputs must be stored in DB to be usable by STDCM.

**Comment by flomonster** [comment]
Done with train schedule v2
