### ISSUE TITLE
[META] Unify all backend errors format

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#3230]
Format was decided in #2697.

1. We need to Change the format of all errors in the services :

- [x] #3183 
- [x] #3192
- [x] #3182

2. Each service need to expose all the possible errors returned (list of keys)

3. CI must send warnings on missing translations keys

<blockquote>
## Error / warning format

This error format must be shared by all backend services.

```json
{
    "type": "invalid_detector",
    "message": "Invalid detector",
    "context": {
        "track_location": {"track": "toto", "offset": 42}
    }
}
```

## Handling operation failure / success

Sometimes, failure is not caused by a protocol error, but by the user request by itself.
The details of how failures are handled depend on the task at hand, so following this format is _not mandatory_.

### Example call failure

This is an example of how 

```json
{
    "status": "failure",
    "warnings": [],
    "error": {
        "type": "no_path_found",
        "message": "No path could be found",
        "context": {}
    }
}
```

### Example call success

```json
{
    "status": "success",
    "result": {}
}
```

## Error discovery

For each backend service, add a command which enumerates possible error types:

```json
[
    {
        "invalid_detector": {
            "message": "Invalid detector",
            "mandatory_context": ["track_location"],
        }
    }
]
```

This list of error messages can used to ensure error messages are properly translated / handled by the front-end.

Actions items:
- [ ] update the website documentation
- [ ] create a CI job which scraps backend error messages and reports the status of front-end translations
- [ ] migrate existing backend error messages

### Acceptance criteria

A list of conditions which define when this task shall be considered complet
</blockquote>

**Comment by anisometropie** [comment]
Use the wrapper { status, warnings, error: {} } only if it’s a legitimate error (like pathfinding returning a 200 when no path exists
do not use the wrapper for 4xx, 5xx
