### ISSUE TITLE
[META] End linter warnings and prevent their return

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#3265]
# Description
Linter warnings on front start are an anomaly. An effort to suppress them was undertaken few months ago but new warnings occurs (alongside new practices). A strategy to get rid of them in one month has been set up.

Files to deadline: https://docs.google.com/spreadsheets/d/1WcPXQsyO1ezotu1U1vSguER916fY_FCADhlAQ1sJNpU/edit#gid=0

Who is responsible for follow-up: @alexandredamiron 

Do we treated all warning currently present: no but the vast majority. The journey is more important.

# Acceptance Criterias Pointage au 21 avril 2023
- [x] import/no-cycle respected, set up as lvl 2 @ouestware srtout dans l'éditor mais il faudra en tolérer
- [x] no-nested-ternary respected, set up as lvl 2 @Math-R en merge
- [x] react/jsx-no-useless-fragment, set up as lvl 2 @Akctarus en merge
- [x] import/no-unresolved (+-2) 
- [x] prefer-const (+-1)
- [x] no-resticted-globals (+-8) on enableIntereactivity
- [x] react/prop-types et no-unused propTypes tout dans Allowances (+-15) -> en cours de résolution sur passage à TS
- [x] +- 15 erreurs sur MarecoMultiRange en cours de suppression
- [x] Le reste principalement du unexpected-any à décider ensemble

- [ ] last warning on editor.ts and set to zero @alexandredamiron
