### ISSUE TITLE
[META] stdcm: change UI to ease the diplay of space-time chart

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#3298]
# Description

The current STDCM interface requires the user to scroll up and down between the inputs and the outputs. The idea is to re-organize the interface so that the results are visible quicker.

# Goal

Improve STDCM user experience.

![Image](https://user-images.githubusercontent.com/765626/226357851-a82c8ffa-5767-4397-a030-6eaffa82330c.png)

# Acceptance criteria

- [x] The map, space-time chart and space-speed chart must use the 2/3 right part of the screen and be displayed in this specific order -> #3609 , @Yohh 
- [x] The other inputs must take the1/3 left part of the screen -> #3609 , @Yohh 
- [x] The rolling stock card must be simplified to fit in one line -> #3610 , @Yohh 
- [x] The itinerary component must follow the first refactor by @alexandredamiron : https://github.com/DGEXSolutions/osrd/issues/3612
- [x] The margins components must be refactored, following these indications : https://github.com/DGEXSolutions/osrd/issues/3611
- [x] The UI must follow the following mockup (coming soon) -> existing draft to be updated after decisions on this point and the last one - non commited

**Comment by axrolld** [comment]
As the #3611 changed from a condensed itinerary version to a refacto in margins components, I suggest the penultimate acceptance criteria should be replaced with :

- [x] The itinerary component must follow the first refactor by @alexandredamiron : #3612 
- [x] The margins components must be refactored, following these indications : #3611

**Comment by alexandredamiron** [comment]
Ok
