### ISSUE TITLE
[META] editoast: generate openapi using crate utoipa

### ISSUE THREAD

**Issue by leovalais** [OpenRailAssociation/osrd#3625]
### Description and goal

Annotate every editoast endpoint with utoipa[1] annotations in order to generate the OpenAPI description.

#### Search endpoint

There is also some refactoring to do for the `/search` endpoint. Currently, the structure of the response is defined in `search.yml` and duplicated in the openapi.yml. Since it will be removed, we need to define the response structure with Rust structs. 

At the meantime, since we're redefining that structure in Rust, we could provide the information of search.yml using macro annotations to get rid of that file. 

```rust
#[derive(Search, ToSchema)]
#[search(table = crate::tables::osrd_search_track, columns(infra_id = AstType::Integer, line_name = AstType::String, line_code = AstType::Integer))]
struct Track {
    #[search(sql = "osrd_search_track.infra_id")]
    infra_id: i64,
    #[search(sql = "osrd_search_track.unprocessed_line_name")]
    line_name: String,
    #[search(sql = "osrd_search_track.line_code")]
    line_code: i64,
}

#[derive(Search, ToSchema)]
#[search(table = ..., columns(...))]
struct Signal {
    ...
}

#[utoipa::path(
    responses(
        (status = 200, description = "...", content(
            ("application/json" = Track),
            ("application/json" = Signal)
        ))
    )
)]
#[post("/search")]
pub async fn search...
```

[1]: https://github.com/juhaku/utoipa

### Acceptance criteria

- [ ] all endpoints are covered (Check this issue for progression)
- [ ] still allows to generate the front's RTK file

#### Search endpoint

- [ ] The `Search` derive macro is defined and `search.yml` is gone

**Comment by leovalais** [comment]
Progress tracking: #4580

**Comment by clarani** [comment]
Done :white_check_mark:
