### ISSUE TITLE
[meta] front : use RTK in front

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#3793]
Follow-up file: teams [architecture/front_quality_follow_up/metrique_migration_rtk]( https://sncf.sharepoint.com/:x:/r/sites/OSRD644GrpO365/Documents%20partages/Architecture/Front%20Quality%20Follow-Up/metrique_migration_rtk.xlsx?d=w4810ae6d804540e3b1e04b24aadb2c53&csf=1&web=1&e=E8gKs4)

- [x] ImportTrainScheduleModal.jsx                            @SharglutDev 
- [x] submitConfAddTrainSchedules.ts                        @SharglutDev 
- [x] ModalPathJSONDetail.jsx                                    @clarani 
- [x] AddOrEditScenarioModal.tsx                               @Uriel-Sautron 
- [x] ~~getTimetable.jsx~~                                            @SharglutDev 
- [x] SimulationResultsMap.tsx
- [x] DriveTrainSchedule.jsx                                        @clarani 
- [x] AddOrEditStudyModal.tsx                                     @SarahBellaha 
- [x] Study.tsx                                                                @SarahBellaha 
- [x] ~~getStdcmTimetable.jsx~~                                 @Uriel-Sautron 
- [x] StdcmRequestModal.jsx                                        @alexandredamiron 
- [x] InfraSelectorEditionActionsBar.jsx
- [x] MapSettingsSpeedLimits.jsx                                   @Uriel-Sautron 
- [x] RollingStockCardDetail.jsx                                     @Yohh 
- [x] RollingStockSelector.jsx                                        @Yohh 
- [x] simulation.js                                                            @Uriel-Sautron 
- [x] ~~StandardAllowanceDefault.jsx~~                      @alexandredamiron 
- [x] simulationResultsHelpers.jsx                                  @Uriel-Sautron
- [x] Timetable.tsx                                                          @nicolaswurtz 
- [x] getSimulationResults.tsx

**Comment by celine-sncf** [comment]
done
