### ISSUE TITLE
[META] Use Kotlin Infra on STDCM

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4003]
####  Description and goal

We need to move from the legacy infra representation to the new version, implemented in kotlin.
This is a necessary step for the integration of the new signaling/conflict system.

Needs #4018 and #4064 to be completed first, as represented here :

![Image](https://github.com/DGEXSolutions/osrd/assets/86296016/0bd4814d-a72b-47ca-9c3d-b7b1ba598f26)

#### Acceptance criteria

- [x] The infra used in the STDCM module is the one defined in `fr.sncf.osrd.sim_infra`.

todo:

- [x] All of the tasks mentioned [there](https://github.com/DGEXSolutions/osrd/issues/4027#issuecomment-1573269155)
- [x] #4261
- [x] #4263
- [x] #4264
- [x] #4265
- [x] #5041
- [x] #5043
- [x] #5042
- [x] #4266
- [x] #5242

Optional / to do later:

- [ ] #4690
- [ ] #4692
- [x] #4693

**Comment by eckter** [comment]
todo:

- [ ] All of the tasks mentioned [there](https://github.com/DGEXSolutions/osrd/issues/4027#issuecomment-1573269155)
- [ ] Add a way to generate an `EnvelopeTrainPath`
- [ ] Add a way to generate a `TrainPath`
- [ ] Add a way to generate an `MRSP`
- [ ] Migrate `STDCMSimulations` 
- [ ] Migrate `RouteAvailabilityLegacyAdapter`
- [ ] Remove any mention of `SignalingRoutes`
