### ISSUE TITLE
MetaTask: Create a documentation website

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#402]
- [x] osrd-project/osrd#403
 - [x] osrd-project/osrd#405
 - [x] osrd-project/osrd#404
 - [x] osrd-project/osrd-website#131

**Comment by multun** [comment]
The website is a thing now!
