### ISSUE TITLE
[META] Migrate pathfinding algorithm in kotlin

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#4027]
## Description

Migrate pathfinding algorithm in kotlin.

Needs #4064 and #4022 to be completed, as represented here :

![Image](https://github.com/DGEXSolutions/osrd/assets/86296016/2ad28a20-9c1f-4258-8754-f89bdcd8da34)

## Goal

Being able to use the new blocks graph.

## Acceptance criteria

- [x] #4271
- [x] #4253
- [x] Migrate pathfinding pre and post processing
  - [x] #4254
  - [x] #4255
- [x] #4256
- [x] #4257
- [x] #4258
- [x] #4259
- [x] #4260
- [x] #4837

All of those tasks except `GraphAdapter` and the validation functions are also required for #4003.

**Comment by eckter** [comment]
todo:

- [ ] Add any missing data to the track (electrification, loading gauge, ...)
- [ ] Migrate pathfinding pre and post processing
  - [ ] Migrate the conversion from track location to route locations (`findRoutes`)
  - [ ] Migrate the postprocessing: `PathfindingResultConverter` (this will take a while)
- [ ] Migrate the constraints
- [ ] Migrate the heuristic
- [ ] Migrate `GraphAdapter`
- [ ] Migrate the validation function

All of those tasks except `GraphAdapter` and the validation functions are also required for #4003.
