### ISSUE TITLE
[META] front: Intervals Editor UI/UX specifications

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#4094]
## Général
- responsive (hauteur et largeur variables)
- produire une documentation de l'API
- pouvoir autoriser ou non des zones vides
- prévoir un undo (dernière action mais idéalement plusieurs ?)

## Amélioration existant
- mettre en place la graduation ordonnée et abscisse (optionnel)
- pouvoir découper à un endroit arbitraire avec les ciseaux
- ajouter des poignées (le curseur change suivant si c'est le début ou la fin >| ou |<) pour faciliter le déplacement des extrémités
- déplacer un intervalle dans sa totalité
- afficher la valeur dans le graphique
- si pas nécessaire, pouvoir avoir une hauteur fixe et commune et faire disparaître la graduation en ordonnée
- les champs de saisie sont collés au graphique en mode horizontal

## Nouveautés
- les outils à droite ne déclenchent pas d'action à la sélection mais au clic une fois le curseur sélectionné
  - la découpe se fait en 1. choisissant les ciseaux 2. déplaçant le curseur là où l'on veut couper 3. clic à cet endroit déclenche la découpe)
  - la glue/fusion fonctionne à l'identique en « collant » ensemble les deux zones qui contient et suit le curseur (celle en dessous et celle juste après) et le nouvel intervalle contient les valeurs du premier
  - la suppression, de la même manière, le curseur se transforme en poubelle, et on clique sur les zones à supprimer. ATTENTION si on est en mode « pas de zone vide » la place vidée est remplie par la zone en amont sur le chemin
- pouvoir tracer un intervalle directement à la souris
- pouvoir saisir les valeurs d'un intervalle (ou cliquer sur deux objets positionnés sur le chemin — PR, signal, etc.)

### Clavier
- les flèches droites et gauche permettent de passer d'une zone à une autre (et si zoomé, le graphique se déplace pour toujours afficher la zone sélectionnée au centre dans ce cas de figure seulement)
- la touche `suppr` efface la zone sélectionnée en cours SAUF si focus sur champ input

### Affichage (et rendre cela activable/desactivable)
- PR
- signaux
- aiguilles
- transitions de vitesse
- électrification 

## Spécificités crans
- pouvoir affecter une valeur via un menu déroulant

## Spécificités marges
- affecter une valeur via une boîte d'invite ou modale
- pour la marge de régularité, toute le chemin doit être couvert, et pour chaque zone un couple type/valeur doit pouvoir être sélectionné
- pour la marge de construction, on peut avoir des intervalles discontinus, et pour chaque zone on doit pouvoir choisir une distribution (linéaire/mareco) et un couple type/valeur

![editeur d'intervalles](https://github.com/DGEXSolutions/osrd/assets/6003856/6725617f-610e-4a76-9a3c-b7f5fd97cb19)

**Comment by axrolld** [comment]
This needs to be splitted into pieces that can fit in one iteration.

**Comment by alexandredamiron** [comment]
Je propose:
Etape 1 0.1 : démonstrateur validé avec  Est 6

- [x] responsive (hauteur et largeur variables)
- [x] pouvoir autoriser ou non des zones vides
- [x] déplacer un intervalle dans sa totalité
- [x] graduation
- [x] "poignées" de déplacement

Etape 2 0.5: Est 6
- [x] Outils glue et découpe
- [x] pouvoir saisir les valeurs d'un intervalle (ou cliquer sur deux objets positionnés sur le chemin — PR, signal, etc.). les champs de saisie sont collés au graphique en mode horizontal. **Format libre, Passage en prop d'un React.Fc formulaire libre qui devra accepter un LinearMetaDataItem.**
- [x] Affichage **+Snapping, clic on** en option: PR, signaux, aiguilles, transition de vitesse. Genéralisé: Passage d'une enumeration d'objets STEPS incluant: symboles, title, liste {distance, name, properties }

Etape 3 1.0: Est 4
Validation + documentation API

Opitionel 1.5:
- [ ] Clavier
- [ ] Undo

**Comment by axrolld** [comment]
Si la première valeur est supprimée, il n'y a pas de valeur amont, à remplir donc avec la valeur aval si "pas de zones vide"

**Comment by axrolld** [comment]
"affecter une valeur via une boîte d'invite ou modale" pour les marges. Pourquoi ne pas saisir une valeur de la même manière que pour le reste, dans la barre horizontale située en dessous ?

**Comment by axrolld** [comment]
@alexandredamiron proposition de découpage mise à jour, qu'on te propose avec @bgiuliana :

Etape 1 v0.5 : estimation 7 j.h #4028 

- responsive (hauteur et largeur variables)
- valeur par défaut 0 ou None-equivalent partout
- création d'intervalle avec le `+` et drag&drop
- graduation abscisse + ordonnée (valeurs si comparables, hauteur fixe sinon)
- "poignées" de déplacement
- suppression
- afficher la valeur dans le graphique
- ajout de {valeurs numérique + unité} ou {single select}

Etape 2 v1.0: estimation 4 j.h

- Validation du composant en l'appliquant aux restrictions de puissance
- Documentation API

Etape 3 v2.0:

- Outils glue et découpe
- Pouvoir autoriser ou non des zones vides
- déplacer un intervalle dans sa totalité (pas "essentiel" si ça fait trop chargé, car peut être remplacé par une suppression-création ou un double déplacement avec la poignée)
- pouvoir saisir les valeurs en cliquant sur deux objets positionnés sur le chemin — PR, signal, etc.)
- Affichage +Snapping, clic on en option: PR, signaux, aiguilles, transition de vitesse. Genéralisé: Passage d'une enumeration d'objets STEPS incluant: symboles, title, liste {distance, name, properties }

Optionnel v3.0:

Clavier
Undo
