### ISSUE TITLE
[META] Implementing E2E tests

### ISSUE THREAD

**Issue by El-Youssef** [OpenRailAssociation/osrd#4132]
## Description
Implementing several E2E tests to ensure the stability of the application. The identified tests are listed below in the Acceptance Criteria section.
## Goal

Implementing the identifies E2E tests 

## Acceptance Criteria

The following tests must be implemented:

- [x] Project creation workflow 
- [x] Study creation workflow 
- [x] Scenario creation workflow 
- [x] Selection of rolling stock 
- [x] Selection of composition code 
- [x] Pathfinding success - Ok local
- [x] Pathfinding error electrification
- [x] Pathfinding missing origin error 
- [x] Pathfinding missing destination error  
- [x] Running time calculation on a given pathfinding - Ok local
- [x] Addition of a regularity allowance 
- [x] Adding a construction allowance
