### ISSUE TITLE
[META] implement dead sections (BP/CC)

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#4145]
# Context
Dead zones (or sections) are sections of track where electrical trains cannot pull power from catenaries. Instead, trains have to rely on inertia to cross such sections.
If the section is designated as a pantograph drop zone, trains will lower pantographs before entering the section, and will start raising pantographs again once the train has entirely left the section.

We decided to use dead zones to represent both cut-off and drop-pantograph sections because in both, the train needs to stop pulling power from catenaries (before dropping its pantograph, the train must cut off the power to avoid electric arcs).

## General details
When the train is in a dead zone, **it has to rely on inertia to cross such sections**. Of course, dead zones **do not affect non electrical rolling stocks**.

Cut-off sections exist to avoid electric arcs. It can happen in several cases:
- ...

Drop-pantograph zones exist because:
- the train need to drop the pantograph to cross a tunnel
- the train is entering/leaving a High Speed Railway or a new track section with a different electrification.

A dead zone should be bidirectional (it means that every train which cross the section should cut the power, independently of its direction), but the panels are not always present on both side of the railway. Indeed, a dead zone can be crossed in the opposite direction in some exceptional cases (in this case, the train conductor should have information about the dead zone).
BUT our pathfinding will be limited by the signalisation, so we should take the direction of the dead zone => **_we will consider all dead zones as bidirectional by default and use TrackRanges to represent them_**.

We need to **take into account the delay to cut-off the power or drop/lift the pantograph**. These times depend on the type of rolling stock: 
|            | Delay to lower pantograph | Delay to lift pantograph | Delay to cut off power | Delay to restart pull power |
|----------|-------------------------------------|--------------------------------|-------------------------------|------------------------------------|
| TGV    | 10s                                     | 25s                                | 0s                                | 5s                                       |
| Autres | 10s                                     | 15s                                | 0s                                | 5s                                       |

To identify an electric train in the RS csv, we need to check that the column "Type" is "Elements automoteurs bimodes ou électriques", "locomotives électriques" ou "TGV".
To identify a TGV in the RS csv, we need to check whether the column "Matériel analysé" contains "TGV" or not.
⚠ these delays are given in seconds (time). In the simulation, once the train has passed the FIN or REV panel, it will have to wait for some time before starting to pull power again.

### Common case
For a **cut-off zone**, the train should meet:
- a announce panel
- an execution panel: the train cannot pull power as soon as its head has passed the execution panel
- an end-of-zone panel: the train can start pulling power again once its tail has passed the end-of-zone panel

For a **drop-pantograph zone**, the train should meet:
- a announce panel (drop pantograph)
- an execution panel: the train should have cut off the power and dropped its pantograph when its head has passed the execution panel
- an end-of-zone panel: the train can start lifting its pantograph again once its tail has passed the end-of-zone panel, and it can start pulling power again as soon as its pantograph is in contact with the catenary

### Push-pull train case
A train is called push-pull train if it has at least one pantograph not located at its head.
If a push-pull train is moving in reverse (which means that at least one of its pantograph is not at its head), it has to wait a special "REV" panel (for reversible) to start pulling power from catenary / lifting its pantograph(s) again (as soon as **its head reaches the REV panel**).
⚠ if the push-pull train is not moving in reverse, then it should not wait the REV panel.

22/05: To manage this case, we have to know whether a train is a push-pull train or not, and whether it is moving in reverse or not. In this first feature, **_we will consider that if the train meets a REV panel, then it has to wait the REV panel to start pulling power again (even if it is not a push_pull_train)._**

### Simulation
_Negociated with Loïc on 15/06_
- the train stops to draw power at the announcement panel
- the train starts to draw power after a special distance after the REV/FIN panel (this distance is computed with the MRSP curve, with the formula `distance = time_to_raise_panto * speed_at_the_end_of_the_section`).

# Implementation details
### Dead zones data
First, we will have to import the dead zone data. Dead zones will be generated from the panels stored the Gaia.
- we will only generate a dead zone if it has at least one execution panel and enough end-of-zone panels. Otherwise, the dead section will be ignored.
- some dead zones only have an execution panel (when the train actually need to switch from electrical to thermal mode). These sections are ignored in this feature.

### Private Data studies 
https://sncf.sharepoint.com/:w:/r/sites/OSRD644GrpO365/Documents%20partages/Documentation/Etudes%20donn%C3%A9es%20Gaia%20BP-CC.docx?d=w343d6ca3e3234c658de80a66823c3977&csf=1&web=1&e=8E8me7

## Model
```python
class DeadZone(BaseObjectTrait):
    track_ranges: List[TrackRange]
    push_pull_track_ranges: Optional[List(TrackRange)]
    is_drop_pantograph_zone: bool 
```

## Implementation plan
- sprint 2
  - [x] railjson/api/osrd_schema: create the deadSection data model and add it in the railjson (#4117)
  - [x] dags: study and import the dead sections data from gaia (https://github.com/DGEXSolutions/osrd-dags/issues/64)
  - [x] railjson/api/osrd_schema: fix the data model (#4194)
  - [x] railjson_generator: add BP/CC to small_infra (#4156)
  - [x] editoast: update the import of railjson (#4182) 
  - [x] editoast: add a dead section layer (for the front cartography module) (#4116)
  - [x] front: display the dead section layer on the cartography (#4116)
- sprint 3
  - [x] core: update the railjson (#4227)
  - [x] core: update pathFinding algorithm (to authorize a RS to cross dead sections and non electrified track sections) (#4227)
  - [ ] editoast/core: add the  BP/CC in the simulation results (#4282)
  - [x] editoast: update the rolling stock model (#4292)
  - [ ] dags: add new fields in the rolling stock import
  - [ ] editoast: update the train schedule model (⚠ dependency) (#4228) (dropped for now)
- sprint 4
  - [ ] core: update the simulation to take into account the dead sections (#4337)
  - [ ] front: display the dead sections in the new Lineary (?) Component (https://github.com/orgs/DGEXSolutions/projects/17/views/1?pane=issue&itemId=27252513)

## To do as soon as possible (20/06)
- [ ] python/editoast: update the model of the dead section to have an announce panel
- [ ] dags: update the import with the announce panels
- [ ] core: update the simulation to start from the announce panel (?)

## To do later
- [ ] implement REV behaviour
- [ ] improve display of BP/CC data
  - [ ] pas d'affichage de la direction pour le moment
  - [ ] give the user to display the REV  
- [ ] add the panels 
- [ ] bp/cc editor
- [ ] rollingstock editor
- [ ] refacto and rename variables
  - deadSection -> neutralSection
  - dropPantograph -> lowerPantograph
  - cutOff -> switchOff

**Comment by Tguisnet** [comment]
This is done.
