### ISSUE TITLE
editoast: add data in get timetable endpoint

### ISSUE THREAD

**Issue by younesschrifi** [OpenRailAssociation/osrd#4366]
# TODO 

Write AC (list of the data to add) 

- [x] heure de départ 
- [x] heure d'arrivée 
- [x] code de composition
- [x] id du path
- [x] vitesse initiale
- [x] les labels
- [x] confort 
- [x] options
- [x] restrictions de puissance

**Comment by flomonster** [comment]
Done
