### ISSUE TITLE
[META] v1 of the intervals editor

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#4431]
## Description

First version of the interval editor with the strict minimal features. Part of #4094. Continuation of #4028 .

## Goal

Grealty improve the UX/UI of allowances, power restrictions, slopes, etc

## Acceptance criteria

- [x] The values of the intervals must be displayed if there's enough space to do so
- [x] Ticks must be responsive and adapt dynamically to the size of the screen (the number of ticks must change).
- [ ] _Numbers of digits to be settable_.
- [x] Non mandatory max interval value sticking to distance if distance = max.
- [x] Debounce on input change for metadata.
- [x] The API is documented

**Comment by axrolld** [comment]
Drag & drop retiré du scope
Comportement à harmoniser avec les autres graphes à l'utilisation
Remplacer le warning en bas à droite par un warning directement dans l'intervalle correspondant
Affichage de l'électrification en dessous des restrictions de puissance si le temps le permet

**Comment by clarani** [comment]
Completed in PI7.
