### ISSUE TITLE
meta: core: stdcm: use the new conflict detection

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#4484]
We need to interface the STDCM module with the conflict detection module to find appropriate results.

This ticket only describes the changes that need to be done on the STDCM side of core.

____

Prerequisites: 

- [x] https://github.com/osrd-project/osrd/issues/4003

To do:

- [x] https://github.com/osrd-project/osrd/issues/6113
- [x] #6154
    - This isn't part of the physical path so it's not part of the previous interface 
- [x] #6285
    - [x] Requires this bugfix: https://github.com/osrd-project/osrd/issues/3482
- [x] #6276
- [x] #6266
- [x] #6274
- [x] #6275
- [x] #6370
- [x] #6621
- [x] https://github.com/osrd-project/osrd/issues/6704
- [x] https://github.com/osrd-project/osrd/issues/6706
- [x] optimization: implement linked lists of `PathProperties` and `EnvelopeStopWrapper` 
    - The simple implementation where everything is concatenated has very poor complexity
    - we need to implement those interfaces from smaller paths / envelopes without copying the data
- [x] optimization: run a profiler to see what need to be improved
    - Several components have been implemented in a "lazy" / inefficient way, we should see which ones are problematic
- [x] cleanup: `BlockAvailabilityLegacyAdapter` should be moved to a test module and renamed accordingly
    - It could be considered legacy and removed, but it's an extremely convenient way to write unit tests
    - `UnavailableSpaceBuilder` should be removed
    - some tests should be updated accordingly
