### ISSUE TITLE
Add utoipa annotations by endpoint family

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#4580]

**Comment by leovalais** [comment]
Work done:

- Generation setup
- `openapi_legacy.yaml` - `openapi.yaml` merging
- Macros `routes!` et `schemas!` to split the declarations across multiple files
- A fair amount of tweaking for RTK compatibility

TODO:

- [x] /rolling_stocks + /light_rolling_stock #5697 @Tristramg 
- [x] /electrical_profiles #5775 @Tristramg 
- [x] /layers #5809 @Tristramg 
- [x] /single_simulation @Tristramg #6153 
- [x] /stdcm #5700 @leovalais
- [x] /pathfinding #5700 @leovalais 
- [x] /infra #4802
  - [x] GET /infra/{id}/routes/{waypoint_type}/{waypoint_id} @leovalais #6338 
  - [x] GET /infra/id/lines/lin_code/bbox @leovalais #6301 
  - [x] GET /infra/id/attached/track_id @leovalais #6304 
  - [x] GET /infra/id/errors @leovalais #6366 
  - [x] GET /infra
  - [x] POST /infra https://github.com/OpenRailAssociation/osrd/pull/7551
  - [x] GET /infra/cache_status https://github.com/OpenRailAssociation/osrd/pull/7551
  - [x] GET /infra/id #7442
  - [x] DELETE /infra/id #7442
  - [x] POST /infra/id https://github.com/OpenRailAssociation/osrd/pull/7553
  - [x] PUT /infra/id #7442
  - [x] POST /infra/id/load #7442
  - [x] GET /infra/id/railjson #7358
  - [x] POST /infra/railjson #7358
  - [x] GET /infra/id/switch_types #7370
  - [x] POST /infra/refresh https://github.com/OpenRailAssociation/osrd/pull/7551
  - [x] GET /infra/voltages https://github.com/OpenRailAssociation/osrd/pull/7357
  - [x] POST /infra/id/lock #7321
  - [x] POST /infra/id/unlock #7328
  - [x] GET /infra/id/speed_limit-tags #7331
  - [x] GET /infra/id/voltages #7344
  - [x] GET /infra/id/routes/track_ranges @leovalais #6338 
  - [x] POST /infra/id/pathfinding (fixes https://github.com/osrd-project/osrd/issues/6317)
  - [x] POST /infra/id/objects/object_type
  - [x] POST /infra/id/clone #7442
- [x] /studies @Tristramg #5463
- [x] /scenarios @Tristramg 
- [x] /search #4590 + #5464 @leovalais 
- [x] /train_schedule #4755 @leovalais 
- [x] /health
- [x] /version
- [x] /documents #5355
- [x] /projects #5410
- [x] /timetable #5044

**Comment by clarani** [comment]
Finally finished :white_check_mark:

**Comment by laggron42** [comment]
🎉
