### ISSUE TITLE
[meta]Intégrer analyseurs dans Osmose

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#4799]

**Comment by Tristramg** [comment]
From different sources, those are possible validators:

- [x] suspicious angles
- [ ] switches with too many edges (medium)
- [ ] switches without `railway=switch` (easy if the above is done)
- [ ] discontinuous ways (might be already implemented)
- [ ] crossing of roads without tunnel/bridges (might be already implemented)
- [ ] shared node between road and rail without `railway=level_crossing`
- [ ] is electrification defined? (easy)
- [ ] is max_speed defined? (easy)
- [ ] missing signaling (hard)
- [ ] incoherent signaling
