### ISSUE TITLE
[META] Improve/Fix E2E tests

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5024]
# BH

Make it possible to run e2e test in the CI and catch new bugs and regressions.

### Current state

E2E tests are disabled since there where several issues:
- Not atomic (tests where depending on a specific state of the db to be successful)
- Complex to maintain, need poetry, back-end and playwright to run
- Repetitive, too of them where checking the same content (all creating project, study and scenario for instance)
- Too much arbitrary timeouts
- Tests where not parallelizable
- Hard to debug (running on both small_infra and infra_france locally)

# AC

- [x] Tests are easily maintainable by frontend developers
- [x] Tests are parallelizable
- [x] Tests are atomics
- [ ] Guidelines are on the website
- [x] Tests are run at each commit in the CI

# Refinement

- [x]  Move setup/tear-down in playwright to remove the dependency to `poetry` and make it fully maintainable by front end developers

This is not too hard, should rewrite poetry fixtures as typescript functions to call them in before, after and setup: https://playwright.dev/docs/test-global-setup-teardown#setup

- [x] Make tests independant (therefore parallizable)
- [x] Only test on small infra, charge tests must be done through another way (human tests,.. )
- [x] Only test chrome and firefox
- [x] Rewrite tests so they test only one specific usecase, therefore atomic (STDCM test should not have to create project/study/scenario, these must have been created in its before* function through apis calls)
- [ ] Add e2e tests guidelines to osrd-website

## Tests that have to be rewrite

- [x] home-page
- [x] project-management
- [x] study-management
- [x] scenario-management
- [x] operational-studies
- [x] stdcm-page
- [x] allowances (Yoh)
- [x] stdcm-between-two-trains (Clara)

## New tests to write

- [ ] simulation-parameters-selection (Romain)
- [ ] rolling-stock-selection (Sarah)

Can be seen as part of https://github.com/osrd-project/osrd/issues/5022 to improve front-end code maintainability

**Comment by Yohh** [comment]
the last refacto are in @Maymanaf 's hands, can be part of #6610
