### ISSUE TITLE
META: front: refacto rollingstock module to adapt it with new front architecture design tree

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#5082]
### Description and goal

RollingStock module need to be adapted to the new front architecture design tree by moving some files in the app

### Acceptance criteria

There should be a : 
- [x] rollingStockEditor folder in the applications folder for this service view
- [x] rollingStock folder in the new modules folder
- [x] components folder with both rollingStockEditor and rollingStockSelector folders containing their components files
- [ ] assets folder containing `migtraffic.json` and `rollingstockDetailDB.json` ?
- [ ] styles folder containing all rollingstock scss files (`RollingStockDarkMode.scss`, `_rollingStock.scss`, `_rollingStockForm.scss`)
- [ ] `rollingstock_opendata2osrd.json` should be moved in assets
- [ ] helpers folder should contain both submodules helpers (separate files)
- [ ] unit tests folder (rsSelector) specific to module are inside module
