### ISSUE TITLE
META : front: refacto rollingstock module to adapt it to new front architecture rules

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#5083]
### Description and goal

RollingStock module need to be adapted to the new front architecture rules

### Acceptance criteria

- [ ] rollingStockEditor folder should have an index.ts for easier imports like the selector one
- [x] RollingStockSelector HOC should be removed ?
- [ ] harmonize props structure and naming (no "Props" but "ComponentProps") in all components by using types (?) 
- [ ] all selector calls (and dispatch ?) should be moved to the view (RollingStockEditor.tsx) and passes down with props drilling
- [x] RollingStockEditorCurves.tsx should be refacto to be less huge
- [ ] helpers/utilities functions in RollingStockEditorCurves.tsx should be moved in the helper folder
- [ ] helpers/utiliers functions in SearchRollingStock.tsx should be moved in the helper folder
- [ ] All complex components or functions should have a description for easier maintainability
- [ ] units tests for the editor ? or e2e only ?
- [ ] rsEditorHelpers should be splited in 2 components (parameter / Metadata) ?
