### ISSUE TITLE
[META] Migrate ManageTrainSchedule module to Comply new guidelines

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#5084]
### Description and goal

The current https://github.com/osrd-project/osrd/pull/5062/files#diff-0ccab85607262df233ab353f11fd27ec5288f5813f0777d8c6795f9708bb6ce3 on going task will move files regarding to this module to new files nomenclature.

The 2nd step consist in making all the components inside this module modest and isolated. They won't call any selector nor do any dispatch nor call any api endpoint through rtk query hook.

We could use the actual 'view' ManageTrainSchedule.tsx as a gateway to prepare this migration.  It will orchestrate the component as the final view will do. 

This is what this view produce:
<img width="2015" alt="Capture d’écran 2023-09-20 à 17 37 30" src="https://github.com/osrd-project/osrd/assets/765626/6b042c4a-a418-4eb0-97d2-b629a09789c8">

It consists in a TrainSettings Div on top, and four tabs. Rolling Stock Selection, Itinerary Definition, Margins Definition, Other Parameter Simulation (Speed Limit, Power restrictions, Electrical Profiles for now)

<img width="1363" alt="Capture d’écran 2023-09-20 à 15 59 55" src="https://github.com/osrd-project/osrd/assets/765626/79ee5a2e-f867-4043-97a7-2412529e6fe8">

Please note that RollingStock is not displayed as dependency whereas it is. Analyser setting issue. 

_So in order to advance simultaneously we have to, for each component, considering that ManageTrainSchedule will act as temporary view, or smart component._

**Strategy**: move selectors calls, actions (actions dispatched, not no pas pass dispatch) and middleware rtk query calls (on editoast) to the ManageTrainScheduleView. 

- [ ] TrainSettings -> **Make a specific PR as this work will be forward-compatible**
    - [ ] Declare TrainSettingsPropsInterface
    - [ ] replace the 4 selectors called by props (mandatory but default value set)
    - [ ] declare onUpdateTrainLabels, onUpdateTrainName, onUpdateTrainDepartureTime, onUpdateTrainInitialSpeed as props (mandatory but noop default)
    - [ ] Ensure theses selectors calls and callback are defined in view and properly passed as prop (or typescript will complain)

- [ ] PowerRestrictionSelector -> **Make a specific PR as this work will be forward-compatible**
    - [ ] replace the selector called by props (mandatory but default value set)
    - [ ] declare onUpdatePowerRestrictionRanges, onSetWarnings (mandatory but noop default)
    - [ ] Ensure theses selectors calls and callback are defined in view and properly passed as prop (or typescript will complain)
    - [ ] Move the consts import from the module consts (if new nomenclature merged)

- [ ] SpeedLimitByTagSelector: This one is already isolated (or dumb) through a HOC. The ehanced component is the one exported by default. This default component is also used bt Stdcm, so beware. **Make a specific PR as this work will be forward-compatible**
    - [ ] Hoc pattern is to be dropped:
        - [ ] Move the declaration inside withOSRDData to the 2 regarding views. 
        - [ ] remove this HOC. Rename IsolatedSpeedLimitByTagSelector to SpeedLimitByTagSelector and rename the default export
    - [ ] use Interface and not types for PropsDeinfition. Dispatch type is not supposed to be necessary. Check other props are mandatory. Do not pass t - i18n

- [ ] ElectricalProfile -> **Make a specific PR as this work will be forward-compatible**
    - [ ] replace the selector called by props (mandatory but default value set)
    - [ ] declare onChange (mandatory but noop default)
    - [ ] Ensure theses selectors calls and callback are defined in view and properly passed as prop (or typescript will complain)

- [ ] Allowances: This Component use subComponents but they are already isolated. So only the main component is to be rewritten -> **Make a specific PR as this work will be forward-compatible**
    - [ ] replace the 2 selector called by props (mandatory but default value set)
    - [ ] pass the data provided by osrdEditoastApi.useGetPathfindingByIdQuery as Props
    - [ ] declare onUpdateAllowances (mandatory but noop default)
    - [ ] Ensure theses selectors calls and callback are defined in view and properly passed as prop (or typescript will complain)

> For Guidelines Redaction: Callback are sometimes invoked after inner ops of the component in a useEffect, should we use sepcific naming (I believe not as onSomeAction means it is a callback dedicated to parent component behavior only)

- [ ] Itinerary : Too deep-nested for now, to be refactored thourgh a coming issue
- [ ] Map: Too deep-nested for now, to be refactored thourgh a coming issue
