### ISSUE TITLE
meta: stdcm: stabilization and optimization for v1

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#5152]
This doesn't replace https://github.com/osrd-project/osrd/issues/3998, it's more specific and only concerns the v1 stabilization/optimization.

It's a collection of things to do and things that would be nice to have, in no specific order. For some, details are included in the issue description (todo). For others, there's no clear plan yet. Most are not assigned, anyone should feel free to pick one.

More issues can be added to this list, feel free to add suggestions.

## Tests

- [x] #5197
- [x] #5198
- [x] #6133
- [x] tests: stdcm: write tests on large infras with many scheduled trains
- [x] #6134

## Stabilization / bugfixes

- [x] #5196
- [x] #5344
- [ ] https://github.com/osrd-project/osrd/issues/5745
- [x] core: stdcm: look for bugs
- [x] core: stdcm: look into existing bugs in running time computations
- [x] #5228
- [x] #5229
- [x] #5329
- [ ] https://github.com/osrd-project/osrd/issues/5436
- [x] https://github.com/osrd-project/osrd/issues/5434
- [x] https://github.com/osrd-project/osrd/issues/5426
- [x] https://github.com/osrd-project/osrd/issues/5400
- [x] https://github.com/osrd-project/osrd/issues/5778

## Optimization

- [x] #5213
- [x] https://github.com/osrd-project/osrd/issues/5513
- [ ] stdcm: identify cases where computation time is too long
- [ ] stdcm: run profilers on cases where the computation time is too long
- [ ] stdcm: improve the heuristic
- [ ] core: optimize mareco
- [ ] stdcm: avoid computing mareco binary search unless strictly necessary
- [ ] core: optimize running time computations

**Comment by eckter** [comment]
Issues that are still relevant today will be tracked in https://github.com/osrd-project/osrd/issues/3998, closing this
