### ISSUE TITLE
[META] Component Robustness: Analyse Some Component behavior with large datasets

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#5368]
The objective is to set tup a way to analyse perf on main interactions in most importants module with heavy payloads, identify components with performance issues

- [ ] Setup scenarii and prepare a reference doc

- [x] Define acceptable perfs and metrics

- [x] Setup storybook-performance-addon

- [x] Make build memory consumption < 1.5gb

- [ ] Setup interaction sample
 
- [ ] Begin with:
    - [ ] GET
        - [ ] Determine actions (sceanrii)
        - [ ] Setup 3 dataset payload 
    - [ ] Map
        - [ ] Use the 3 dataset payload 
    - [ ] TrainList
    - [ ] GEV

- [x] on Every svg output, record number of dom elements

**Comment by clarani** [comment]
Not relevant anymore
