### ISSUE TITLE
[META] Magic wand in editor :magic_wand:

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5521]
> [!IMPORTANT]
> EDIT on Jan 16th 2024 : we're closing this and keeping track of the leftover work [here](https://github.com/osrd-project/osrd-confidential/issues/317).

## Description

- Add a "magic wand" button in the editor
- Using it generates a list of modifications.
  - A modal appears, giving statistics on changes. (Nb: of deletion, modification, addition)
  - Then the user can chose to apply these changes or cancel the operation

### List of errors that should be fixed by the magic wand

- [x] #5921 

#### Delete objects (Can be done before the code refactoring)

- [x] Detector Buffer Stops or Signal: Invalid Ref (track) -> Remove the object
- [x] #5857 -> Remove the route
- [x] #5861  -> Remove switch
- [x] #5863  -> Remove the object
- [x] #5866  -> Create a buffer stop 
- [x] #5867  -> Remove the object
- [x] https://github.com/osrd-project/osrd/pull/5969 -> Remove the object
- [x] https://github.com/osrd-project/osrd/pull/6009 -> Remove the object
- [x] Node endpoint unicity (created [here](https://github.com/osrd-project/osrd/pull/6172)) -> Remove the object

#### Update objects (needs code refactoring first)

- [x] #5856 -> Remove track range from the Speed section / Catenary
- [ ] #5858  -> Remove release detector from Route
- [ ] #5859  & #5860 -> Search for new path and take the first one matching all the valid switches
- [ ] #5943 -> Clamp used track-section

## Technical description

- A `GET` endpoint (`/infra/{}/auto_fixes/`) must be added. It generates a payload of modifications to fix the infra.
- The front can inspect this payload, and count the number of deletions, modifications, and additions.
- If the user wants to apply this. The front needs to call the existing endpoint `/infra/{}/edit/` with the payload received earlier.

**Comment by axrolld** [comment]
`Switch: Unknown port name -> Remove object`

@Erashin noticed that this might cause and avalanche of errors because the other ports (tracks) of the switch won't have a switch anymore. Will this cause the creation of many buffer stops ? Or Make the tracks invalid ?

Should we transform the switch into a new one with one port less ?

**Comment by axrolld** [comment]
`Out Of Range -> Clamp the offset to [0;track_length]`

What happens when we shorten the beginning of the track ?

**Comment by axrolld** [comment]
`Empty object: Remove the object`

Seems like this is a warning and not an error, why do we want to fix this with the magic wand ? And what exactly is considered an empty object and how to reproduce it ?

**Comment by flomonster** [comment]
> `Switch: Unknown port name -> Remove object`
> 
> @Erashin noticed that this might cause and avalanche of errors because the other ports (tracks) of the switch won't have a switch anymore. Will this cause the creation of many buffer stops ? Or Make the tracks invalid ?
> 
> Should we transform the switch into a new one with one port less ?

This can lead only to new warnings, not errors. A switch can't have one port less it will be marked as an invalid switch and result in an equivalent error.  


> `Out Of Range -> Clamp the offset to [0;track_length]`
> 
> What happens when we shorten the beginning of the track ?

What do you mean by shortening the beginning of the track? If you mean change the geometry of the track, then all objects on this track will have their geometry updated (this is already handled). You can only change the `length` of the track and this can result into `OutOfRange` errors.



> `Empty object: Remove the object`
> 
> Seems like this is a warning and not an error, why do we want to fix this with the magic wand ? And what exactly is considered an empty object and how to reproduce it ?

It's a warning that's easy to fix automatically, so why do without it? To reproduce it you need to define a speed limit (or catenary) without attaching it to any tracks.

**Comment by axrolld** [comment]
> What do you mean by shortening the beginning of the track? If you mean change the geometry of the track, then all objects on this track will have their geometry updated (this is already handled). You can only change the length of the track and this can result into OutOfRange errors.

I mean that OutOfRange can only imply position greater than `track_length`, as no object can be under position zero. I'm affraid this will happen :
![image](https://github.com/osrd-project/osrd/assets/86296016/0afc9c7f-892c-45c4-b7d6-fd42bb965f95)

**Comment by axrolld** [comment]
Checked with study officers, the `Out Of Range` should result in a deletion of the object, so that it can be re-created manually after.

Specific case for buffers stops, because if removed a `Buffer stops not found` error would be created, so a new buffer stop need to be created again.

**Comment by axrolld** [comment]
## Front part implementation proposition

### Option 1

Magic wand button next to the error/warning counter (bottom right)

![Option 1](https://github.com/osrd-project/osrd/assets/86296016/3bdfe975-8fae-49da-a747-db4e93296ef3)

It should be hidden or visible whether the errors layers is active or not.

### Option 2

Magic wand as part of the edition tools (because it is an other edition tool). This might imply moving the number of errors next to it (so to the left).

### In both cases

Clicking the button opens a modal window.

![Option 1 loading](https://github.com/osrd-project/osrd/assets/86296016/cee0ef63-588c-460b-92df-f4664b18c998)

Modal pops up with a loader and a message `Computing possible fixes`, waiting for the payload (~a few seconds), then convert it into the statistics of creation, modification, deletion of objects.

![Option 1 appliquer](https://github.com/osrd-project/osrd/assets/86296016/73113bd5-7dcf-4d1a-b97c-b4808f7ef23c)

A Cancel button must be visible during loading, allowing the user to get back to the map (won't cancel the call in backend but no need). Confirm/apply button should be disabled during loading.

Confirm/Apply button become clickable once the statistics are displayed.

No upper-right cross to close the modal (because of the cancel button).

**Comment by bloussou** [comment]
we have chose option 1 in "po sync" :)

**Comment by thibautsailly** [comment]
Here is the magic wand icon, to be displayed at 24px size.
![wand-24](https://github.com/osrd-project/osrd/assets/870509/d813aabd-0a9e-40f8-83eb-647a690856b4)

**Comment by nicolaswurtz** [comment]
@axrolld you can't omit the cross : clicking outside modal, closing browser do the same. You should add a specific button that really cancel the running action, and be explicit about it.

**Comment by Erashin** [comment]
Seen with @nicolaswurtz and @axrolld: we don't keep the cross.

**Comment by bougue-pe** [comment]
@axrolld : subtask https://github.com/osrd-project/osrd/issues/5943 was added, as discussed with @flomonster we should clamp in those cases (open to discussion).

**Comment by woshilapin** [comment]
Summary of a meeting about priority rules for operations on objects.

First, an important hypothesis is: **an operation always targets the same object that the corresponding error is targeting** (at the notable exception to `CREATE` which will generate a new ID). It's an important hypothesis because it can technically unlock performance optimizations (parallelizing by object).

Multiple operations may happen on all the errors associated to an object: `CREATE`, `UPDATE`, `DELETE`. In the end, a maximum of one operation per object should remain. Note that a list of errors on one object A may still result in multiple operations if there is creation of new objects: but there will be only one final operation (or no operation) on A.

Here are the possible combinations of operation on the same object and the expected resulting operation:
- `CREATE` + `CREATE` = **NO OPERATION**
  * it shouldn't happen to have 2 `CREATE` operations with the same object's identifier
  * log `ERROR`
- `CREATE` + `UPDATE` = **`CREATE` with the updated object**
  * log `WARN`
- `CREATE` + `DELETE` = **NO OPERATION**
  * log `ERROR`
- `UPDATE` + `CREATE` = **NO OPERATION**
  * log `ERROR`
- `UPDATE` + `UPDATE` = **`UPDATE` (JSON patch combining the 2 updates)**
  * keeping the order is important, the RFC of JSON patch ensure the order matters
- `UPDATE` + `DELETE` = **`DELETE` (ignore the `UPDATE`)**
- `DELETE` + `CREATE` = **NO OPERATION**
  * log `ERROR`
- `DELETE` + `UPDATE` = **`DELETE` (ignore the `UPDATE`)**
- `DELETE` + `DELETE` = **`DELETE`**

When `WARN` log is expected: the situation looks weird, but maybe there is a good reason that we did not plan for. Let's report the case in logs and investigate it to see if it's a valid case (and remove the warning if valid).
When `ERROR` log is expected: the situation should not happen, and it's most likely a bug, we need to investigate why.

Any other succession of operations can be simplified by reducing them two by two. For example, if you have `CUUUD` (`C` for `CREATE`, `U` for `UPDATE`, `D` for `DELETE`), here is how it would be reduced:
- `CUUD` (`CU` is reduced into a unique `C` with the combined modifying operations)
- `CUD`(`CU` is reduced into a unique `C` with the combined modifying operations)
- `CD` (`CD` is reduced to no operation)
- `NO OPERATION`

**Comment by axrolld** [comment]
I'm closing this, keeping track of the leftover work [here](https://github.com/osrd-project/osrd-confidential/issues/317).

Other actions might be added in the future, but everything will be kept in this new issue, or even future versions of the magic wand. This issue was the first version that reached a totally acceptable state, so we're closing this.
