### ISSUE TITLE
[Meta] Make the project more welcoming

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#584]
# Analysis

## Target audience

- `R` researchers
- `S` students
- `E` railway software engineers

## Use cases

- `R,S` optimization research (interactive backend)
- `E` driving simulator (interactive backend)
- `R,(E)` standalone use of envelopes, as a library (backend only)
- `E` path finding services (backend only)
- `E` running time calculations (front + back)

## Contribution scenarios

- `R,E,S` bug fixing
- `R,E` design improvements
- `R,E` implement new signaling systems
- `E` implement data inter-exchange modules (to / from RailJSON)
- `R` integrate optimization algorithms
- `R,E` add interactive simulation features

# TODO

- [ ] `R,E,S` Setup an instant messaging room
- [x] `R,E,S` Make the project easier to install and use
- [x] `R,E,S` Write contribution guidelines
- [x] `R,E,S` Write an architecture guide
- [x] `R,E,S` Write a _adding a new signaling system_ guide
- [ ] `R,E,S` #402
- [ ] `S` Prepare student projects
- [ ] `S` Join GSOC
- [x] `S,E` Prepare good first issues
- [ ] `E,R` Make a guide showing off standalone use of envelopes
- [ ] `R` Write papers on OSRD internals
- [x] `R` Go talk at research conferences
- [ ] `R` Advertise OSRD on research mailing lists (create a mailing list?)
- [x] #898

**Comment by flomonster** [comment]
Legacy
