### ISSUE TITLE
Design an infrastructure edition API

### ISSUE THREAD

**Issue by multun** [OpenRailAssociation/osrd#602]
- [ ] ability to perform any change on the infrastructure
 - [ ] cope well with data that is regenerated when objects change
    - [ ] this should be quick
    - [ ] if slow, the front-end should be able to perform optimistic guesses
 - [ ] be compatible with versioning
 - [ ] integrated with the backend?

**Comment by flomonster** [comment]
# Suggestion 1 (22/02/2022)

## Databases:

- Lakefs: Handle versioning.
- Postgresql: Two sets of tables
  - Active copies (for each branch)
    - Doesn't contains information about TVD Sections (these are generated)
  - Generated data (for each branch) 

## Algorithm

```
new_objects, deleted_objects, object_patches = parse_changes(query)

# TODO: infer changes if deemed necessary

# lock the branch to update the active state
pg_select_for_update(branch)

# push the changes to lakefs
updated_objects = {
    apply_patch(fetch(object), patch)
    for object, patch in object_patches
}
commit = lakefs_commit(new_objects + updated_objects, deleted_objects)

# update the commit the branch points to, and update the active copy changelog
update_branch(branch, commit, changes)

# apply the changes to the active state
pg_apply_changes(branch, changes)

# complete the transaction
pg_commit()

# request an asynchronous update of all cache tables.
# some of these cache tables are directly updated inside the database,
# whereas some others depend of worker daemons, which rely on the changelog to 
# update their internal state to AT LEAST the current commit.
# these caches include:
#  - geometry of point objects positioned on track sections
#  - route geometry
#  - geometry of speed sections / catenary / signaling type regions
#  - errors
# These caches need to read the current state with `repeatable READ` isolation level 
# to guarantee consistency between the commit hash and data content
update_caches(branch, changes) 
```

## Implementation

### General information

This service can be implemented in `Java` or `Rust`.
Each instance needs to cache infras and metadata. 
osrd-core will have to download the whole infra each time we make a change.

### First implementation simplications

- we don't have to use `lakefs`.
- the CRUD api can accept single change

### What must be done

- Remove `TVDSection` from railjson
  - Change route railjson format (define release groups with detectors instead of tvd sections)
  - Adapt osrd-core
- Adapt infra schema (it must not contain generated data sush as detectors geometry...)
  - This schema is railjson `v2.1.0 `
  - We must adapt infra import / export
- Create generated data models
- Merge chartos with osrd-api
- Create the new edition service
  - CRUD service (simple)
  - Apply patch (simple)
  - Generate data from patch (difficult)

## New architecture

![Architecture OSRD fr Edition drawio](https://user-images.githubusercontent.com/15349030/155307133-3548fe00-f260-446b-9c97-df3e57b3b2bd.png)

## Names ideas

- Edition (lack of style)
- Nabu (God scribe)
- Editos (Open source editor)
- Thoth (Egyptian deity)
- Hachette / Editis
- Chisel / Rusted chisel
- Chalk
- editeRS 
- papyrusT
