### ISSUE TITLE
Remove "applicable_directions" field from detectors

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#6083]
## Description

Currently, detectors have a field `applicable_directions`. This field is never used and should be removed from the schema.

## Goal

Simplify forms removing unused fileds

## Acceptance criteria

- [ ] The field `applicable_directions` is removed from the schema.

## Tasks

- [x] Remove the fields from `python/osrd_schemas/osrd_schemas/infra.py`
- [x] Bump the railjson version
- [x] Adapt railjson generator library
- [x] Check that example infra generation scripts still work
- [x] Adapt editoast
- [x] Adapt core (only bump railjson version). The `applicable_directions` field should already be ignored.
- [x] Write a migration (the down.sql can set the field to `BOTH`)
- [x] Generate the new `front/reducers/osrdconf/infra_schema.json`. It's generated by `python/osrd_schemas/osrd_schemas/infra.py`. The CI checks that this file is sync.
- [x] Check that the editor is working properly
- [x] Update the website documentation

**Comment by Khoyo** [comment]
This may impact dags too, we need to make sure it still works after the change
