### ISSUE TITLE
[META] Replace osrdConf state by two independant state (simulationConf & stdcmConf)

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#6143]
create two independant slices for stdcm and operationalStudy (simulation). and replace the osrdConf by the new two slices

- [x] [Create STDCM and simulation slices ](https://github.com/osrd-project/osrd/issues/5272)
- [x] [remove simulationConf section inside osrdConf and use simulationConf from root store](https://github.com/orgs/osrd-project/projects/20/views/32?pane=issue&itemId=41092936)
- [x] [remove stdcmConf section inside osrdConf and use stdcmConf from root store](https://github.com/orgs/osrd-project/projects/20/views/32?pane=issue&itemId=41093039)

**Comment by clarani** [comment]
Done :white_check_mark:
