### ISSUE TITLE
meta: core: stdcm: adjust both sides of the resource generation API to fit our need

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#6370]
- [x] #6416
- [x] #6417
- [x] #6371
- [x] #6372
- [x] #6403
- [x] #6418 
- [x] #6419

STDCM requirements: we want to be able to know, at a single point in space/time, all conflicts that happen *at that time*. Conflicts that will happen later on (even on the same resources) will be identified and avoided later on. 

"Not enough lookahead" means "we need more info to know the *current* state of the resource use".

We also need to know the time of the next conflict, and, if a conflict happens, how much delay we would need to add to avoid it.

------

Updated version, to do:

- [x] #6568
    - [x] Implement the new class
    - [x] Write tests + fix
- [x] https://github.com/osrd-project/osrd/issues/6418
- [x] #6567
    - [ ] When no conflict:
        - [ ] How much delay we can add
        - [ ] Start time of next resource use
    - [ ] When there is a conflict
        - [x] Minimum delay to add to the departure time to avoid the conflict

**Comment by eckter** [comment]
Updated version, to do:

- [x] core: implement the resource generation module to include "not enough path" and partial resource uses
    - [x] Implement the new class
    - [x] Write tests + fix
- [ ] Use the conflict detection module instead of comparing resource uses by hand
- [ ] core: add missing info to the conflict results
    - [ ] When there aren't any conflicts:
        - [ ] How much delay we can add
        - [ ] Start time of next resource use ~We can use the ID of next train instead, this is less confusing~ train id should not be used: in the case of 2 ressources used by different trains starting at the same time, the start time would correspond to both resources, whereas the train id won't.
    - [ ] When there is a conflict:
        - [ ] Minimum delay to add to the departure time to avoid any conflict
        - [ ] offset of the first conflict ~ID of the train we're in conflict with~ same reason as above
        ~- [ ] TODO: figure out if the list of train IDs is an issue~
