### ISSUE TITLE
Speed limit edition and usage with no value fails

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#6407]
### What happened?

When we create a speed limit with no default value `0` is given to editoast.
Core behavior is weird having a speed limit of `0` (it uses the rolling stock speed limit).

### What did you expect to happen?

- [x] Front should provide a `null` speed limit when not provided (allowed by the model) => #6428
- [x] Editoast should expect speed greater than `0` => #6436
- [x] Core should expect speed greater than `0` => #6436
- [x] We could provide a migration to transform all `0` speed to `null` => #6436

### How can we reproduce it (as minimally and precisely as possible)?

1. Use this [infra](https://github.com/osrd-project/osrd/files/13992351/Broken.Infra.id5.railjson.json)
2. Create a train (left to right)
3. Its MRSP should be `80km/h`

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

572a549e28a1e551b873cef3c9d4e7888e03654b
