### ISSUE TITLE
stdcm: refactor: avoid dealing with absolute envelopes when possible

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#6917]
Currently, when exploring the stdcm graph, we keep track of precise envelopes at any given point. We actually keep two for each edge: one for the the "maximum speed" envelope ("marche tendue"), and another one scaled down to account for the standard allowance used for conflict detection. 

Then, during the post-processing, we concatenate the maximum speed envelopes and apply the standard allowance on that, with several iterations to avoid any new conflict.

The maximum speed envelopes *contain the engineering allowances*. This is the tricky part. It means we need to actually compute precise envelopes that match the engineering allowances. This is extremely expensive, both in terms of memory use and execution time. 

---

An alternative solution would be to drop the maximum speed envelopes entirely. We still compute them and extract some data (start/end speed, running time) but they're not stored. We only check that the engineering allowances are physically reachable, but we don't need to *precisely* compute them either. We would only need to identify some fixed times for given points, which matches the "train schedule v2" interface for allowances. 

---

### Why is this useful?

* It would let us fix https://github.com/osrd-project/osrd/issues/6915 without having "weird" allowances
* Lots of computations would not be required anymore, leading to *significant* optimizations (both in terms of speed and memory). I believe it's *required* to have reasonable execution time when engineering allowances are involved.
* Matching the train schedule v2 interface may mean not having to maintain different versions
* It would lift some constraints for the running time simulation API
* I'd assume it would make the post-processing part more stable

### Implementation plan

This plan still has some uncertainties, there's a possibility a change has more implications that what was originally planned.

- [x] Step 1: #6981
    1. Re-compute the "max speed" envelope from scratch, ignoring engineering allowances
    2. Rely exclusively on fixed times to hint at engineering allowances and to avoid conflicts
- [x] Step 2: #6982
    1. We'd need at least start/end speeds and total time
- [x] Step 3: #6983
- [x] Step 4: #6984
- [x] Step 5: #6985
- [ ] Optional (if we need more ram): get rid of the scaled envelopes used for conflict detection [*only if we can make approximations there*]
    - Actually we *can* do that, but *only when there is a standard allowance*. In real-life scenarios that is always the case, but we don't want to make it actually mandatory 
- [ ] Optional (speed optimization): implement a better heuristic to determine if the train can go slow enough
- [x] Cleanup: some parts of `STDCMEdgeBuilder` may become outdated. Website documentation should be updated. 

---

Follow up:

- [ ] https://github.com/osrd-project/osrd/issues/7136
    - We currently run simulations with maximum speedup / slowdown, but this will be incompatible with the next version of running time simulations
    - We may be able to find an analytical solution if we estimate bounds for accelerations / decelerations
- [x] Test and measure speed improvements, see what could be improved
    - There are still some timeouts going on, we should try to find what goes wrong
    - We could import paths and timetables from private SNCF data and run benchmarks on those 
- [ ] Write doc
