### ISSUE TITLE
META: adapt trainScheduleResults

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#7023]
### Description and goal

Technical precisions
- [ ] add a new piece of the store, osrdSimulation v2
- [ ] use the new endpoints: projection of the trains on a path, fetch the trains of a timetable, get selected train details 

### Acceptance criteria

 - [ ] the user can display the trains of the scenario, select one, change the projection and use the graphs and map as before
- [x] if a train cannot be simulated, then a warning notifies the user in the list of the trains
- [ ] on the map, the user can only see the selected train
- [x] check on DriverTrainSchedule that it can still be exported in csv
- [x] the conflicts are still displayed as before
- [ ] we can still update a train

### Maquettes
- the unvalidated trains have a warning
![Image](https://github.com/osrd-project/osrd-confidential/assets/55697979/6812664b-725b-4143-89e2-da50e6d35b82)

**Comment by clarani** [comment]
Not relevant anymore
