### ISSUE TITLE
[META] front: remove v1/v2 switch and v1 components

### ISSUE THREAD

**Issue by clarani** [OpenRailAssociation/osrd#7028]
### Description and goal

Technical precisions:
- [x] delete all the old components
- [x] clean the store

Implementation plan
- https://github.com/OpenRailAssociation/osrd/issues/8059
- https://github.com/OpenRailAssociation/osrd/issues/8060
- https://github.com/OpenRailAssociation/osrd/issues/8063
- https://github.com/OpenRailAssociation/osrd/issues/8064
- https://github.com/OpenRailAssociation/osrd/issues/8065
- import
- stdcm

### Acceptance criteria

- [x] v2 switch has disappeared, all the workflows use the v2 endpoints (scenario creation, train creation)

**Comment by clarani** [comment]
This issue can be closed now :white_check_mark:
