### ISSUE TITLE
Isolate `editoast::schema` into an `editoast_schemas` crate

### ISSUE THREAD

**Issue by hamz2a** [OpenRailAssociation/osrd#7048]
# Description and goal

Part of #6397 

Isolate the `schema` module of editoast into its own crate `editoast_schemas`.

**The crate goal is to define the schemas of the different railway objects that can be imported and exported by editoast.**

As such, some modules currently present in `editoast::schema` shouldn't be included in `editoast_schemas`.
Is expected in `editoast_schemas` (List of schema files to move to `editoast_schemas` #7085) :

* all railjson infra objects
* the railjson format of a rolling stock
* the railjson format of a train schedule
* all type wrappers should be in a `editoast_schemas::primitives` module

Is expected to be removed or refactored out of `editoast::schema`:

- [x] the editor CRUD, which can be temporarily moved into `editoast::infra_cache` #7086 
- [x] `RollingStockCommon` should become `RollingStock` and everything else should be deprecated in favor of their respective models
- [x] `schemas/utils/geometry.rs` should be in `editoast_common` #7111
- [x] `sprite_config` should be in `editoast_generation`, but can be temporarily moved into `editoast::generated_data` #7075
- [x] `geo_json` should be deprecated in favor of the `geojson` crate (re-exported by `geos`)

# AC

- [x] `editoast_schemas` crate is created within editoast's workspace
- [ ] All schemas must implement `Debug`, `Serialize`, `Deserialize`, `ToSchema` (and `PartialEq` when it makes sense, likewise for `Eq`)
- [ ] All schemas defined in a file must be included in a `schema!` expression
- [x] All schemas defined in the crate are available using `editoast_schemas::schemas()` (generated using `schema!`)
- [x] Infra objects are defined
- [x] Rolling stock is defined
- [x] Train schedule is defined
- [x] `editoast::schema` module is removed
- [x] All pertinent unit tests are ported and pass
- [ ] No regression is observed
- [ ] The crate's public API is as minimal as possible
- [ ] The schemas are well documented
- [ ] The CI has been adaptated
