### ISSUE TITLE
front: adapt updating train v2

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#7488]
Refers to #7023 

### Description and goal

Update a train from the timetable with the new train schedule v2 endpoints

### Acceptance criteria

- [ ] we can still open the train update interface by clicking on the pen icon in the timetable train card
- [ ] when entering the interface, all of the train infos are already displayed (start time, path, margins...)
- [ ] updating a train update it also in the timetable

### Implementation plan
- add a new state value in ScenarioV2 (trainIdToEdit or EditingTrainId ?) to store the id of the train which is currently being edited by the user
- in TimetableTrainCardV2, in editTrainSchedule, remove the updateTrainScheduleIDsToModify dispatch and only setTrainIdToEdit instead
- in ScenarioV2, pass trainIdToEdit to ManageTrainScheduleV2 as a props
- in ManageTrainScheduleV2, pass the trainIdToEdit to the useSetupItineraryForTrainUpdate. This hook will dispatch in the store the correct data so the tabs are correctly pre-filled with the train data

- in the hook, you should:
  - fetch the whole trainSchedule from the backend with its id
  - fetch the other data you need to fill the store:
    - rollingStock (used to fetch the pathBlocks, and to get the data for the powerRestrictions)
    - pathBlocks (used to fetch the pathProperties)
    - pathProperties
  -  fill the following data in the store:
      - rollingStockId & rollingStockComfortV2
      - pathSteps: correspond to the steps of the path of the train. You should merge the data from path, schedule and margins.
      - initialSpeed
      - labels
      - usingElectricalProfiles
      - speedLimitByTag
      - powerRestrictionRanges
      - startTime
