### ISSUE TITLE
 Create osrd_nge and test project of communication with an iframe

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#7536]
1st step of meta #7535 

## Acceptance criteria

- [x] NGE is customizable according to OSRD needs (can run without back-end)
- [x] Only NGE workspace is displayed (not the project management and authentication menus)
- [x] `osrd-nge` is available as npm package
- [x] A test `iframe` proves the communication between `osrd-nge` and NGE

## Implementation plan

- [x] DevOps:
  - [x] (Angular) Create `osrd-nge`: a wrapper (Angular app) that embed a build of NGE with specific settings for OSRD use (standalone mode) ([see POC](https://github.com/osrd-project/osrd-nge-poc))
  - [x] Build and publish [`osrd-nge`](https://github.com/osrd-project/osrd-nge-poc) in npm
  - [x] Import `osrd-nge` from npm and make the NGE build available within OSRD build
- [x] Implement in NGE (with the help of Adrian):
  - [x] (Angular) Back-end separation if standalone flag (around [`version-control.service.ts`](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/src/app/services/data/version-control.service.ts))
  - [x] (Angular) [eventEmitter](https://v17.angular.io/api/core/EventEmitter) on trainrun actions (create, update, delete) (set `environment.customElement`)
  - [x] (Angular) Enable / disable NGE UI elements (authentication and project management components) to keep only workspace (`netzgrafik`) and filters (see [Angular ngIf](https://angular.fr/directives/ng-if)) (set `environment.disableBackend`)
- [x] Implement in `osrd-nge`:
  - [x] [event listener](https://developer.mozilla.org/fr/docs/Web/API/EventTarget/addEventListener) for OSRD data load
  - [x] [event listeners](https://developer.mozilla.org/fr/docs/Web/API/EventTarget/addEventListener) for NGE actions to be triggered on any change (callback from eventEmitter)
- [x] Create a test [iframe](https://developer.mozilla.org/fr/docs/Web/HTML/Element/iframe) project which logs all trainrun actions and has a timetable upload button using [postMessages](https://developer.mozilla.org/fr/docs/Web/API/Window/postMessage) and [eventListeners](https://developer.mozilla.org/fr/docs/Web/API/EventTarget/addEventListener).

## Description

NGE will be refacto to be customizable for the use of OSRD (= without back-end, aka standalone mode).

A minimalist Angular project, named `osrd-nge`, will embed the whole application NGE, named `nge-app`, with custom settings.

Concept diagram:

![OSRD-NGE Concept diagram](https://github.com/OpenRailAssociation/osrd/assets/57864277/fc52939b-c02a-4475-933f-c7f8ca62ebea)

### DevOps / NGE deployment

Create `osrd-nge`, import `nge-app` to build it ([see POC](https://github.com/osrd-project/osrd-nge-poc)) and publish it in npm.

Don't forget to set `nge-app` with standalone flag.

Once it's done, import the build of `osrd-nge` from npm and build NGE for `osrd-front`.

### Split front-end / back-end

Supported by Adrian, enable / disable functions and components in NGE front-end official repos, depending on the value of the standalone flag.

See [`version-control.service.ts`](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/src/app/services/data/version-control.service.ts) (one of the back-end links should be there)

See [Angular ngIf](https://angular.fr/directives/ng-if).

See [POC of disabling NGE back-end](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/pull/128), to be reproduced in NGE at a larger scale.

### Communication through [`customElement`](https://v17.angular.io/guide/elements)

See [current work](https://github.com/osrd-project/osrd-nge-poc/tree/custom-element)

### Payloads

See [Trainrun data model](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/src/app/models/trainrun.model.ts) and [TrainrunSection data model](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/src/app/models/trainrunsection.model.ts)

**Create** `trainrun`:
```javascript
TrainrunSectionOperation {
    "type": "create",
    "trainrunSection": TrainrunSection
}
```

**Update** `trainrun`:
```javascript
TrainrunOperation {
    "type": "update",
    "trainrun": Trainrun
}
```

**Delete** `trainrun`:
```javascript
TrainrunOperation {
    "type": "delete",
    "trainrun": Trainrun
}
```

### Resulting POC

The resulting test project should be enough preparation to ease next step of integration (front-end integration and OSRD to NGE communication, through `osrd-nge`)

Contacts: @louisgreiner (SNCF Réseau) - @aiAdrian (SBB CFF FFS)

## Definition of ready

- **PO**
  - [x] Acceptance criteria are clear and understandable

- **Technical**
  - [x] If required documentation is available on osrd.fr
  - [x] Implementation plan is detailed and validated by maintainers

- **General**
  - [x] WSJF values are filled
  - [x] Validated by the PM
