### ISSUE TITLE
Being able to switch between the OSRD interface and the NGE interface

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#7537]
2nd step of meta #7535  

## Acceptance criteria

- [x] `osrd-nge` runs in operational studies panel
- [x] Microscopic / Macroscopic switch works
- [x] NGE is displayed in operational studies panel when Macroscopic switch is ticked
- [x] Microscopic switch switches back to simulation view

## Implementation plan

- [x] Integrate the osrd-nge [iframe](https://developer.mozilla.org/fr/docs/Web/HTML/Element/iframe) in operationnal studies panel and add the `Microscopic / Macroscopic` switch
- [x] OSRD (front) implements (taking inspiration of the [previous work](https://github.com/osrd-project/osrd-nge-poc/tree/custom-element):
  - [x] enable load of data from OSRD to NGE (template to be found in description) (OSRD->NGE)
  - [x] [event listeners](https://developer.mozilla.org/fr/docs/Web/API/EventTarget/addEventListener) for NGE actions (with empty payloads, to be filled with converter) (OSRD<-NGE)

## Description

Use resulting POC from https://github.com/OpenRailAssociation/osrd/issues/7536.

![OSRD-NGE Concept diagram](https://github.com/OpenRailAssociation/osrd/assets/57864277/fc52939b-c02a-4475-933f-c7f8ca62ebea)

### `osrd-nge iframe` display

It should look like a new "tab" in OSRD (not a browser tab) that enable to switch view from either simulation view of a scenario or the iframe that embed `osrd-nge`. The selected tab is slightly highlighted.

The iframe points to the running `osrd-nge` project.

The `Microscopic / Macroscopic` switch should look like this, switching views from simulation to NGE:
![image](https://github.com/osrd-project/osrd-confidential/assets/57864277/ce0ee868-b620-422e-9fce-84d31880f6ea)
![image](https://github.com/osrd-project/osrd-confidential/assets/57864277/2a325b8f-0878-4153-8459-236dc2e8fa28)

Docs: 
- [`eventTarget.addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener):
- [`EventEmitter`](https://v17.angular.io/api/core/EventEmitter)

-> See below example

```mermaid
---
title: OSRD - NGE Sequence diagram
---
sequenceDiagram
  autonumber
  OSRD (osrd_window)-->>OSRD (osrd_window): init web page
  OSRD (osrd_window)->>NGE (nge_iframe): set `netzgrafikDto` DOM property
  loop while synchronization is ON
    alt any modification in OSRD (osrd_window)
      OSRD (osrd_window)-->>OSRD (osrd_window): any modification
      OSRD (osrd_window)->>NGE (nge_iframe): set `netzgrafikDto` DOM property
    else any modification in NGE (nge_iframe)
      NGE (nge_iframe)-->>NGE (nge_iframe): any modification <br>(hooks)
      NGE (nge_iframe)->>OSRD (osrd_window): send `operationX` event (@Output)
      OSRD (osrd_window)-->>OSRD (osrd_window): convert NGE operation into <br/>timetable update
      OSRD (osrd_window)->>NGE (nge_iframe): set `netzgrafikDto` DOM property
    end
  end
```
 
## Definition of ready

- **UX**
  - [x] A wireframe is ready
  - [x] A mock-up is ready

- **PO**
  - [x] Acceptance criteria are clear and understandable

- **Technical**
  - [x] If required documentation is available on osrd.fr
  - [x] Implementation plan is detailed and validated by maintainers

- **General**
  - [x] WSJF values are filled
  - [x] Validated by the PM
