### ISSUE TITLE
NetzGrafik-Editor (NGE) translation

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#7540]
## Description

This issue is a direct contribution to [NGE front-end official repository](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend).

`i18n` interface already exists in NGE for German / English (default) / French / Italian, but is empty. The purpose of this issue is set the `i18n` attribute on the right front-end elements, and to fill the static translation tables.

We aim to improve the quality of the app by refactoring the `.xlf` translation tables to `.json`.

See:
- Angular documentation - [Angular Internationalization](https://v17.angular.io/guide/i18n-overview)
- [How to Internationalization (i18n) in Angular](https://medium.com/@ayushgrwl365/a-guide-to-internationalization-i18n-in-angular-a6ca7a9bc027)
- [`ngx-translate-extract`](https://github.com/biesbjerg/ngx-translate-extract)
- https://phrase.com/blog/posts/best-libraries-for-angular-i18n/
- https://github.com/ngx-translate/core#ngx-translatecore--

Contacts: @louisgreiner (SNCF Réseau) - @aiAdrian (SBB CFF FFS)

## Acceptance criteria

- [x] Can switch between German / English / French / Italian language
- [x] German translation table is complete
- [x] English translation table is complete
- [ ] French translation table is complete
- [ ] Italian translation table is complete
- [ ] No regression for German
- [ ] English has been reviewed by business side
- [ ] French has been reviewed by business side
- [ ] Italian has been reviewed by business side
- [ ] (synchronized with OSRD)

## Implementation plan

- [x] Use [`ngx-translate-extract`](https://github.com/biesbjerg/ngx-translate-extract) to extract translations and create `.json` translation files instead of `.xlf`
- [x] Set `i18n` label to the elements that need translation
- [ ] Fill the translation tables -> [already created here](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/tree/main/src/i18n)
- [ ] Review from business side

## Definition of ready

- **PO**
  - [x] Acceptance criteria are clear and understandable

- **Technical**
  - [x] Implementation plan is detailed and validated by maintainers

- **General**
  - [x] WSJF values are filled
  - [x] Validated by the PM
