### ISSUE TITLE
[META] Adding E2E tests

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#7706]
### Description and goal

Some functionalities are not tested with e2e-tests, we have to complete our battery of tests

### Configuration

- [x] Add Webkit ( Safari !) #8645 => Removed #10478
### Acceptance criteria

Tests to write:

- [x] Rolling stock editor 
  - [x] refacto creation #7763 
  - [x] update #7763 
  - [x] delete #7774 
  - [x] Filtering and searching #7826 
- [x] Operational studies 
  - [x] Rolling stock #7911
  - [x] RS +Route #7912
  - [x] Times & stops #8646
  - [x] Simulation Settings #8647
  - [x] Full operation : RS+ Route + Times & stops + Simulation Settings #8648
- [x] Import of trains ( infra et train de test)
  - [x] Simulation Results (The visibilty of each element) #8040
  - [x] Filtering  #8040
  - [x] Verify the data of each train (RS + Route + Times & stops + Simulation Settings) #8649
  - [x] Import / Export 
- [x] Last Minute Request
  - [x] #9265
  - [x] #9585
  - [x] Simulation sheet
  - [ ] ~~Debugging mode~~
- [x]  Simulation Results
  - [x] GET #9586
  - [x] GEV  #8651
  - [x] Output Table #8646 and #8647
  - [ ] ~~Simulation sheet (pdf)~~
  - [ ] ~~Export csv~~
  - [ ] ~~Carto~~ (complicated to test for the moment and lower priority)
- [x] Timetable management #8650
  - [x] Delete train
  - [x] Duplicate train
  - [x] Multiple selection
  - [x] Searching 
  - [x] Train details
- [ ] ~~Roles and permissions~~
  - [ ] ~~Roles #9588~~
  - [ ] ~~Permissions~~
