### ISSUE TITLE
[META] Handle multiple simulations in STDCM

### ISSUE THREAD

**Issue by Akctarus** [OpenRailAssociation/osrd#8052]
### Description and goal

Be able to create several simulations with different inputs, navigate between them, and select the one that suits you best. 

### Acceptance criteria

- [ ] Obtain one or more simulations
- [ ] Switch between simulations and observe corresponding inputs and results

Mockup : https://www.sketch.com/s/15e0909c-f17d-4200-a770-b9fc1154fa7e/p/CA8C9E9A-B795-4C87-9CF5-508DD0B3634A/canvas

### TODO : 

- [x] Add "Available simulation" message : https://github.com/OpenRailAssociation/osrd/issues/8056
- [x] Add "Upgrade STDCM" div : https://github.com/OpenRailAssociation/osrd/issues/8127
- [x] Change simulation table results onClick : https://github.com/OpenRailAssociation/osrd/issues/8125 
- [x] #8143
- [x] Add "No simulation found" div : https://github.com/OpenRailAssociation/osrd/issues/8128
- [x] #8157

**Comment by Tguisnet** [comment]
Done
