### ISSUE TITLE
Tracking issue • Post-axum migration improvements

### ISSUE THREAD

**Issue by leovalais** [OpenRailAssociation/osrd#8178]
Tracking issues for problems in the `axum` migration PR #8047.

We decided to solve these problems afterwards in other PRs as #8047 is large and conflicts with everyone. It also blocks #8171.

- [ ] Design a replacement for the `routes!` macro
- [ ] Naming and homogeneity pass (good first issue)
- [ ] [Implementing our own otel middleware](https://github.com/OpenRailAssociation/osrd/pull/8047#discussion_r1684411285) to stop using `axum-tracing-opentelemetry` and check the need for `TraceLayer`
- [ ] [evaluating `axum_typed_multipart` and test liveries import](https://github.com/OpenRailAssociation/osrd/pull/8047#discussion_r1687963958) (good first issue)
- [x] #8673
- [ ] Rename `document_key` to `document_id` in `/document` APIs (good first issue)
- [x] #8674
