### ISSUE TITLE
Converting times from NGE to OSRD

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#8389]
### Description and goal

Part of ticket https://github.com/OpenRailAssociation/osrd/issues/7539

The goal of this issue is to have the conversion of times written in NGE to write them in the `train_schedule` in OSRD

### Acceptance criteria

- [ ] The time of the first node of the `trainrun` in NGE is converted as the start time in OSRD (NGE gives minutes only, so the hour is arbitrarly chosen to 8h)
- [ ] The time of intermediate nodes of the `trainrun` in NGE are converted as time contraints on the corresponding points in OSRD :  
    - [ ] arrival time at the node is the arrival time for the point in OSRD
    - [ ] if there is no stop in NGE, there is no stop in OSRD
    - [ ] if there is a stop in NGE, there is a stop in OSRD and the stopping time is computed as the difference between the departure and the arrival time
- [ ] The time of the last node of the `trainrun` in NGE is converted as a time constraint on the last point in OSRD : 
    - [ ] arrival time at the node is the arrival time for the point in OSRD
    - [ ] the stopping time is 0  

### Implementation plan

- [ ] The time of the first node of the `trainrun` in NGE is written in the `start_time` attribute in OSRD
- [ ] For other nodes
  - [ ] the arrival is written in `arrival` of the `path_item` for the attribute `schedule` in OSRD
  - [ ] if there is no stop, the `stopFor` attribute of the `path_item` for `schedule` in OSRD is `None`
  - [ ] if there is a stop, the `stopFor` attribute of the `path_item` for `schedule` is the difference between the departure time and the arrival time
- [ ] The `consecutiveTime` from NGE must be used to know which hour to write in the `arrival` attribute (5 means 8h05 but 65 means 9h05 for example)
