### ISSUE TITLE
osrdyne: Horizontal scaling for one infrastructure

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#8408]
# Description :

If a queue is full of messages for an infrastructure then new instances for this ijnfrastructure should be provided to dequeue messages faster ! 

# Implementation plan

⚠ complex work has it is a fine tuning ⚠ 

1. Implement rust types for kube/keda api
2. Add scaling object and defined a scaling policy (depending on the number of messages waiting in the queue)
4. tests tests tests

# Acceptance Criteria : 

- [ ] Be able to spawn multiple pods for an infrastructure instance if messages are not processed fast enough

## Definition of ready

- **PO**
  - [x] Acceptance criteria are clear and understandable

- **Technical**
  - [x] Implementation plan is detailed and validated by maintainers

- **General**
  - [x] WSJF values are filled
  - [x] Validated by the PM

**Comment by ghost** [comment]
Currently stuck, cannot test the changes as the test environment is broken. Need to await for an external action within the SNCF to fix it.
