### ISSUE TITLE
osrdyne: correlate core pod memory and cpu to infrastructure

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#8409]
# Description :

`core` services are consuming a lot of memory. This memory is correlated to the size and complexity of the infrastructure.

CPU request can also be correlated to the size of the infrastructure.

Because:
1. it will decrease the cost
2. small infrastructure can be provisionned on an existing node so it should be faster
3. make the 🌍 great again

# Implementation plan

will be designed by https://github.com/osrd-project/osrd-confidential/issues/644

# Acceptance Criteria : 
- [ ] All pods have reasonable request for cpu and memory
- [ ] Pods are not stopped for too much memory or cpu consumption 

## Definition of ready

- **PO**
  - [x] Acceptance criteria are clear and understandable

- **Technical**
  - [ ] If required documentation is available on osrd.fr
  - [ ] Implementation plan is detailed and validated by maintainers

- **General**
  - [x] WSJF values are filled
  - [ ] Validated by the PM

**Comment by flomonster** [comment]
Duplicate of https://github.com/osrd-project/osrd-confidential/issues/644
