### ISSUE TITLE
Display infrastructure status in the frontend

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#8410]
# Description :

This is not working anymore: 
![image](https://github.com/user-attachments/assets/7b901e5c-d16f-4895-86e9-f4d8a101a677)

# Implementation plan

Frontend part is already done, calls to editoast to get infra status is just responding `ready` atm.

1. osrdyne must be able to tell if the pod has loaded an infra or not (adapt `/status` to information of pod readiness)
2. editoast must call `/status`

- 1 sprint to know if the infrastructure is `none` or `live`
- 1 sprint to have all the statuses

# Acceptance Criteria : 

- [ ] infra has 5 states `none`, `scheduled`, `pending`, `running`, `live`
- [ ] one `live` pod for one infrastructure is enough to tell that infrastructure is `live`

## Definition of ready

- **PO**
  - [x] Acceptance criteria are clear and understandable

- **Technical**
  - [x] Implementation plan is detailed and validated by maintainers

- **General**
  - [x] WSJF values are filled
  - [x] Validated by the PM

**Comment by celine-sncf** [comment]
Scope reduction proposal: instead of having 5 statuses that are not very clear to the end user, have only 3 statuses  `None, Loading, Ready`

**Comment by louisgreiner** [comment]
## Tested in Recette (26/09/24)

- 0 to 7 scale: 
  - it still displays the loading on a scale from 0 to 7 (and not 3 statuses as [mentioned above](https://github.com/OpenRailAssociation/osrd/issues/8410#issuecomment-2371278697))
  - the hover displays `INITIALIZING` (or `CACHED`) (which is neither `None, Loading, Ready`, shouldn't it be translated ?
![Image](https://github.com/user-attachments/assets/30f04878-7052-40c1-8b83-aa261725a2a8)
  - 1 to 7 takes a long time then instantly finishes
- the editor is well disabled when infra is loading.

![Image](https://github.com/user-attachments/assets/a1978468-0bd6-4c8e-898c-e0a459948872)
