### ISSUE TITLE
Add roles check to endpoints

### ISSUE THREAD

**Issue by hamz2a** [OpenRailAssociation/osrd#8446]
### Description and goal

views:
- [x]  `documents.rs` #8425
- [x]  `electrical_profiles.rs` #8425
- [x]  `layers.rs` #8479
- [x]  `light_rolling_stocks.rs` #8362
-  ~~`mod.rs`~~
- [x]  `projects.rs` #8401
- ~~`scenario.rs`~~ **(tsv1)**
- [x]  `search.rs` #8469
-  ~~`single_simulation.rs`~~ **(tsv1)**
- [x]  `speed_limit_tags.rs` #8468
- [x]  `sprites.rs` #8510
- [x]  `study.rs` #8401
- ~`timetable.rs`~ **(tsv1)**
- [x]  `work_schedules.rs` #8466
- [x] `stdcm_search_environment.rs` https://github.com/OpenRailAssociation/osrd/pull/8641

views/infra:
- [x]  `attached.rs` #8361
- [x]  `edition.rs` #8361
- [x]  `errors.rs` #8361
- [x]  `lines.rs` #8361
- [x]  `mod.rs` #8345 
- [x]  `objects.rs` #8361
- [x]  `pathfinding.rs` #8361
- [x]  `railjson.rs` #8361
- [x]  `routes.rs` #8361
- [x]  `auto_fixes/mod.rs` #8361

views/v2:
- [x]  `scenario.rs` #8401
- [x]  `timetable.rs` #8445
- [x]  `train_schedule.rs` #8436

views/v2/path:
- [x]  `pathfinding.rs` #8449

views/v2/timetable:
- [x]  `stdcm.rs` #8424

views/v2/train_schedule:
- [x]  `projection.rs` #8447

views/rolling_stocks:
- [x]  `mod.rs` #8362

---
~~views/pathfinding~~: **(tsv1)**
- `electrical_profiles.rs`
- `electrifications.rs`
- `mod.rs`

~~views/stdcm~~:
- `mod.rs` **(tsv1)**

~~views/timetable:~~ **(tsv1)**
- `import.rs`

~~views/train_schedule:~~ **(tsv1)**
- `mod.rs`
- `projection.rs`
- `simulation_report.rs`

### Acceptance criteria

add roles check to all endpoints
