### ISSUE TITLE
Remove SBB header

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9269]
## Description

Enabled by [Synchronize OSRD/NGE locale #8569](https://github.com/OpenRailAssociation/osrd/issues/8569), since the current header is the only way to change locale in NGE.

We want to remove this header band, highlighted in yellow:

![Image](https://github.com/user-attachments/assets/9762a080-c18e-4ffa-b982-651a4804389c)

This feature has to be done on our forked repository : https://github.com/osrd-project/netzgrafik-editor-frontend

Note : to work with the forked repo, to keep it clean, thanks for following the guidelines in README

## Acceptance criteria

- The header is not visible anymore
- Changes have been made only on the forked repository (/!\ clean commit message + follow README)
- The size of the iframe has been recalculated taking in account the size saving (no scroll bar or empty space, follow the mock-up)

## Implementation plan

- [ ] Create branch on forked repo
- [ ] Remove header with minimal changes
- [ ] Commit with message "hack: remove sbb header"
- [ ] Merge `new branch -> standalone`
- [ ] Bump package version (see [npm version](https://www.npmjs.com/package/@osrd-project/netzgrafik-frontend)) in OSRD

**Comment by clarani** [comment]
Closed by https://github.com/OpenRailAssociation/osrd/pull/9760
